### ISSUE TITLE
Start new session with same config as an existing project

### ISSUE THREAD

**Issue by jlipps** [tmuxinator/tmuxinator#143]
I have a tmuxinator project called 'dev' which is like a skeleton dev setup I can use for lots of different purposes. When I call `mux start dev` it gets me into one session. I want something like `mux start-clone dev` that gets me into a new session with all the same tmuxinator config, only a different tmux session.

Is there a way to do this already?

**Comment by mumboFromAvnotaklu** [comment]
You can achieve this using this:
```
<% if @args[0] %>
<% WDIR=@args[0] %> 
<% else %>
<% WDIR=ENV["PWD"] %>
<% end %>

name: <%= WDIR.split('/').last  %>
root: <%= @args[0] %>

windows:
  - editor:
      layout: f5f0,238x64,0,0{166x64,0,0,0,71x64,167,0,1} 
      panes:
        - vim:
          - vim -p src/Lib.hs test/Spec.hs
        - tests:
          - stack test --file-watch''
 ```
 [source](https://dev.to/qmenoret/dynamic-templates-with-tmuxinator-4mkh)
