### ISSUE TITLE
default-path option removed in tmux 1.9

### ISSUE THREAD

**Issue by saamalik** [tmuxinator/tmuxinator#170]
The default-path option has been removed in tmux 1.9:

http://sourceforge.net/mailarchive/forum.php?thread_name=20131019080624.GA13382%40SUNGPAE&forum_name=tmux-users

**Comment by mickours** [comment]
This is still a problem. The workaround do not work when you use ``$PWD`` as value.

**Comment by dpino** [comment]
Variable `PWD` didn't work for me either. I was trying to use it from `.tmux.conf`. It seems inside the configuration file is possible to refer to the current path via the variable `pane_current_path`. For instance:

```bash
# Split pane and open up a shell at the bottom keeping the current path.
bind s splitw -v -p 25 -c '#{pane_current_path}' '/bin/bash'
```

**Comment by nathantech2005** [comment]
default-path was working for me. then it stopped working. I didn't change the tmux version. Something more serious is happening.
