### ISSUE TITLE
tmuxinator breaks Home and End keys in fish shell

### ISSUE THREAD

**Issue by seanh** [tmuxinator/tmuxinator#176]
Hey, I don't know what's going on, but the Home and End keys work fine in my fish shell both inside and outside of tmux, but when in any tmux session started by tmuxinator, the Home and End keys break. They just insert `[1~` and `[4~` into the fish command-line, instead of moving the cursor as they should.

**Comment by swistak35** [comment]
I had the same problem, it's tmux fault, not tmuxinator. Check out http://stackoverflow.com/questions/18600188/home-end-keys-do-not-work-in-tmux

**Comment by ethagnawl** [comment]
@seanh I'm unable to reproduce this issue on Debian 8. 

Could you confirm that you're still seeing it using Tmuxinator 0.8.0 and, if there's still a problem, provide some additional information about your OS, Fish version, etc.?

**Comment by seanh** [comment]
I don't remember whether I did something to fix it, but the problem isn't happening for me anymore with my current setup
