### ISSUE TITLE
tmuxinator commands should return non-0 when there's something wrong

### ISSUE THREAD

**Issue by rightaway** [tmuxinator/tmuxinator#192]
For example if $EDITOR isn't set, 'tmuxinator doctor' still returns 0. Makes 'tmuxinator doctor' command less useful for detecting whether things are set up right from scripted installations of tmux and tmuxinator.

Also if you run 'tmuxinator command-that-does-not-exist' it gives a 'Command does not exist' but still returns 0.

There may be other cases where it's returning 0 incorrectly but I haven't come across those yet.

**Comment by ethagnawl** [comment]
@rightaway and @Soliah, please see PR #350.

**Comment by Soliah** [comment]
Fixed by #350.
