### ISSUE TITLE
version comparison method incompatible with versioning scheme

### ISSUE THREAD

**Issue by tek** [tmuxinator/tmuxinator#213]
as of 1.10, the comparison `version < 1.7` yields wrong results.

**Comment by Soliah** [comment]
I can't reproduce this.

**Comment by tek** [comment]
well, tmux is version 2 now, but it should be obvious without test case that `1.10.to_f` results in `1.1`, which is `< 1.8`.
https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/config.rb#L30
