### ISSUE TITLE
Default to first window

### ISSUE THREAD

**Issue by stilliard** [tmuxinator/tmuxinator#218]
Hi, is there a way to set a default window to select after the others have been loaded?
E.g. i have a project with 4 windows, and I'd like it to leave me on the first window, rather than how it currently leaves me on the 4th.
If nothing yet could we add a default_window option maybe? or a post hook so we could set `tmux select-window -t 0`.
Or should it already work like this?

**Comment by Soliah** [comment]
This should be handled by #282

**Comment by mahemoff** [comment]
For people searching, this goes in tmuxinator.yml:
```
startup_window: logs
