### ISSUE TITLE
Autostart a Tmuxinator project on bootup under Ubuntu

### ISSUE THREAD

**Issue by jonasrk** [tmuxinator/tmuxinator#224]
Hey there, thanks for your work.

I know this is not a tmuxinator bug, but can someone help me with this issue nevertheless? I did not get any feedback on stackoverflow ...

http://stackoverflow.com/questions/23269764/autostart-a-tmuxinator-project-on-bootup-under-ubuntu

Copy of the Stackoverflow text:

I have configured a __Tmuxinator project__ I want to have running on my server at all times. What bugs me is that I did not manage to get it to __start automatically__ after (unexpected) reboots. Here's what I have tried so far:

1. Editing __/etc/rc.local__ so that it now contains:

        mux start project &
        exit 0

2. (Following [this guide](http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html)) creating a script that contains
      
        case "$1" in
            start)
            echo "Starting muxproject"
            mux start project
            ;;
and configuring it with

        sudo update-rc.d NameOfYourScript defaults
3. (From the same guide:) Editing __etc/xdg/lxsession/LXDE/autostart__ and adding the line
    
        @mux start project
to it.

None of the above has worked. How can this be achieved?

**Comment by Soliah** [comment]
Handled now by #293
