### ISSUE TITLE
Killing processes when switching to different project

### ISSUE THREAD

**Issue by jpstokes** [tmuxinator/tmuxinator#248]
It would be cool if tmuxiinator had an optional custom kill switch that would execute when switching from one active project to another.

For example I'm running foreman which starts a number of processes but all these processes can be ended manually with ctrl+c. Same with stopping rails server.

This optional kill switch would perform actions of the custom kill switch so that when you switch to another project that used some of these same processes it won't be any conflicts.

This would further help automate getting a dev environment up and running and ready for coding!

**Comment by Soliah** [comment]
This is really out of scope for tmuxinator (IMO). Please have a look at https://github.com/jlipps/tmux-safekill
