### ISSUE TITLE
Can't open project on Debian

### ISSUE THREAD

**Issue by mircsicz** [tmuxinator/tmuxinator#272]
$ tmuxinator monitor
/var/lib/gems/1.8/gems/tmuxinator-0.6.9/lib/tmuxinator/project.rb:22:in `windows': undefined method `with_index' for #<Array:0x7f1dbb068918> (NoMethodError)
        from /var/lib/gems/1.8/gems/tmuxinator-0.6.9/lib/tmuxinator/project.rb:103:in `windows?'
        from /var/lib/gems/1.8/gems/tmuxinator-0.6.9/lib/tmuxinator/config.rb:82:in `validate'
        from /var/lib/gems/1.8/gems/tmuxinator-0.6.9/lib/tmuxinator/cli.rb:50:in `start'
        from /var/lib/gems/1.8/gems/tmuxinator-0.6.9/bin/tmuxinator:13
        from /usr/local/bin/tmuxinator:23:in `load'
        from /usr/local/bin/tmuxinator:23

here's the layout that I tried to use, which works on MacOS: http://paste.debian.net/136248/

**Comment by verganis** [comment]
Same issue here. Just updated to ruby 1.9.3, still won't work

**Comment by Soliah** [comment]
@verganis Passes CI on Ruby 1.9.3 so it might something localised. Feel free to open another issue if you've got problems. Closing this one for now.
