### ISSUE TITLE
Tmuxinator can't read $EDITOR in tmux 1.9?

### ISSUE THREAD

**Issue by syndbg** [tmuxinator/tmuxinator#277]
OS: XUbuntu 14.04
tmux: 1.9
tmuxinator: 0.6.9

Outside of tmux session:
```
▶ mux doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes
▶ echo $EDITOR
vim

▶ mux open odin
# works!
```

But when in a tmux 1.9 session it doesnt read $EDITOR, even though it's set:
```
▶ mux doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> No
Checking if $SHELL is set ==> Yes
▶ echo $EDITOR
vim

▶ mux open odin
sh: 1: /home/syndbg/.tmuxinator/odin.yml: Permission denied
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> No
Checking if $SHELL is set ==> Yes
``` 

The after effects from the above bug is that I can't open or create new projects.

**Comment by syndbg** [comment]
I just restarted zsh, tmux, tmuxinator a lot and after many unsuccessful attempts, it worked the next day.

No idea if this is a issue in tmuxinator or it's just me, so I'm closing the issue. Will re-open if it comes up again.

**Comment by kerams** [comment]
This just happened to me on a fresh VPS installation. I've got tmux 1.9a and Ruby 2.2.0 and tmuxinator 0.69. Just like in your case, `$EDITOR` is clearly set to vim, but mux doctor reports it as missing.

**Comment by kerams** [comment]
Turns out it's not a problem of tmuxinator.

    ruby -e "p ENV['EDITOR'].nil?"
    true

    echo $EDITOR
    vim

    ruby -e "p ENV['SHELL'].nil?"
    false

    echo $SHELL
    /user/bin/zsh
https://www.ruby-forum.com/topic/214260 seems to be related, I am logged in as root...

**Comment by mudmanc4** [comment]
For tmux version 1.9 run 
`update-alternatives --list editor`
Which will print
`/bin/ed
/bin/nano
/usr/bin/vim.gnome
/usr/bin/vim.tiny
`
Then 
`export VISUAL=vim.gnome`

You may be required to take further steps to make this permanent

**Comment by cotterjd** [comment]
This was happening to me because I was using `sudo` and I guess the `EDITOR `for the root user wasn't set even tho it was set for my user. Doing the command without sudo worked.
