### ISSUE TITLE
ssh into remote machine works but and doing sudo -i and running command after that does not 

### ISSUE THREAD

**Issue by ageekymonk** [tmuxinator/tmuxinator#285]
I am trying to use tmuxinator to ssh into multiple machine and run commands as sudo su. I am using the below .yml file to do so. My command "cat /etc/openvpn/openvpn-status.log" does not run at all. 

name: mgmt
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - skymgmt:
             - ssh user@mymachine
             - sudo -i
             - password
             - cat /etc/openvpn/openvpn-status.log
        - skymgmtwf:
             - ssh user@myanothermachine
             - sudo -i
             - password
             - cat /etc/openvpn/openvpn-status.log

The following command fails. Is there a way to achieve this ?

**Comment by Soliah** [comment]
You'll need to provide more info. Please use markdown: https://guides.github.com/features/mastering-markdown/ when posting configs and debug statements.

Please post `mux debug yourproject` output.
