### ISSUE TITLE
Sourcing tmuxinator.zsh file

### ISSUE THREAD

**Issue by jwgoh** [tmuxinator/tmuxinator#287]
Hello there,
I am trying to source the completion file for zsh using source ~/.bin/tmuxinator.zsh but it gives the an error. For some reason tmux command is executed with the argument 'zsh'. I can't figure out the problem.

Many thanks in advance!

![screenshot from 2015-02-23 23 49 12](https://cloud.githubusercontent.com/assets/6704206/6330844/a6abbcd4-bbb6-11e4-90c4-52c1f396a9ed.png)

**Comment by Soliah** [comment]
Ah sorry I haven't released the latest changes on master which is what the completions require. Will be cutting a release today.

**Comment by Soliah** [comment]
Just pushed v0.6.10 to Rubygems which should fix this.

**Comment by jwgoh** [comment]
Excellent, it works now! Thanks a lot :)

**Comment by jwgoh** [comment]
Works like a charm now, thanks a lot :+1:
