### ISSUE TITLE
^@u% printed before prompt when starting tmux

### ISSUE THREAD

**Issue by leonormes** [tmuxinator/tmuxinator#291]
tmuxinator does not open correctly. A new sesion in tmux prints `^@u%` before the prompt and a u after it, and if vim loads it reports that no more undo as if the u key was pressed. 
I think these characters maybe what is interferring with mux not, for instance, moving to the root dir. I have tried removing all conf files for tmux and zsh but still get those characters. 
I ran `tmux -v` and in the log found;

`complete key u 0x75`
`input_parse: '^' ground`
`input_parse: '@' ground`

and so on.

Do you know where this is coming from and how to get rid of it?

Thank you

**Comment by positron** [comment]
Is that related to this issue? http://superuser.com/questions/629227/tmux-prints-12c-whenever-i-start-it-or-re-attach-to-a-session-in-cygwin

**Comment by Soliah** [comment]
Doesn't seem to be related to tmux. Closing.
