### ISSUE TITLE
Ability to create unnamed windows

### ISSUE THREAD

**Issue by kennykaye** [tmuxinator/tmuxinator#292]
My understanding is that currently, windows must have names. Sometimes I prefer the window name to simply be the process which is currently running.

Is there an option to do this?

**Comment by youdulayo** [comment]
+1

**Comment by podung** [comment]
+1.  Completely agree.

**Comment by podung** [comment]
As a workaround, try this:

```
name: default
root: ~/
windows:
  - main:
    - tmux set-window-option -t1 automatic-rename on
    - clear
```

See the discussion around:  https://github.com/tmuxinator/tmuxinator/issues/174

**Comment by davejamesmiller** [comment]
+1

**Comment by verilucis** [comment]
:+1:
