### ISSUE TITLE
Cannot start project whose name is prefix of already running project

### ISSUE THREAD

**Issue by lorrin** [tmuxinator/tmuxinator#297]
I have a project `foo` and a project `foo_prod`. If I start `foo` first, I can then launch `foo_prod`. But if I start `foo_prod` first, then running `tmuxinator start foo` just connects to the existing `foo_prod` session. I wish there was a way to force it to launch the `foo` project without having to resort to using `tmux kill-session` to kill the running `foo_prod` session.

**Comment by DustinArmstrong** [comment]
+1

**Comment by epogue** [comment]
+1

**Comment by Soliah** [comment]
Addressed by #273.

**Comment by lorrin** [comment]
I've confirmed my issue is fixed as of 0.6.11. Thanks so much!

**Comment by lorrin** [comment]
Hmm. Not sure this is totally fixed after all. Given running session `foo_bar` and defined projects `foo` and `foo_bar`, I observe with 0.6.11:
* `mux start foo` does the wrong thing, opening the existing `foo_bar` session
* `mux start foo foo` does the wrong thing, opening the existing `foo_bar` session
* `mux start foo quux` does the right thing, opening a new `foo` session with alternate name `quux`
