### ISSUE TITLE
Commands Have Stopped Working

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#299]
When starting a new session, the commands are each printed twice, but don't seem to be executed. 

![2015-04-29-143209_1600x900_scrot](https://cloud.githubusercontent.com/assets/289949/7398367/89a4c470-ee7c-11e4-843e-3edfe7435289.png)

env:

- lubuntu 14.40
- tmuxinator 0.6.10
- tmux 1.9 (looks like it's not officially supported, but I've been using it for months without issue)
- rvm 1.26.11
- ruby 2.2.0

test.yml

```
# ~/.tmuxinator/test.yml

name: test
root: ~/

windows:
  - editor: vim

```

debug:

```
#!/bin/bash

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session -t test 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /home/peter

  # Run pre command.
  

  # Create the session and the first window.
  TMUX= tmux new-session -d -s test -n editor -c /home/peter


  # Create other windows.


  # Window "editor"
  
  tmux send-keys -t test:0.0 '' C-m
  tmux send-keys -t test:0.0 vim C-m

  tmux select-layout -t test:0 main-vertical

  tmux select-pane -t test:0.0

  tmux select-window -t 0
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t test
else
  tmux -u switch-client -t test
fi
```

**Comment by Soliah** [comment]
That looks like there might be something wrong with the .yml file as it's adding an extra send-keys statement. Either that or something has changed in the YAML parser. Here is what I get when I run `debug`:

```
#!/usr/local/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session -t test 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /Users/Soliah

  # Run pre command.


  # Create the session and the first window.
  TMUX= tmux new-session -d -s test -n editor


  # Create other windows.


  # Window "editor"

  tmux send-keys -t test:1 vim C-m

  tmux select-window -t 1
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t test
else
  tmux -u switch-client -t test
fi
```

Notice the single send-keys statement. Can you double check your yaml config doesn't have any stray characters.

**Comment by ethagnawl** [comment]
@Soliah Thankfully, I'm no longer seeing this particular issue, wherein the commands would stop working entirely. (I reformatted a few weeks back, partially because of this issue.) 

However, if I spin up a new Tmuxinator project and then debug it, I do still see the duplicate send-keys entries:

```
#!/bin/bash

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session -t wat 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /home/peter

  # Run pre command.
  

  # Create the session and the first window.
  TMUX= tmux new-session -d -s wat -n editor -c /home/peter


  # Create other windows.
  tmux new-window  -t wat:1 -n server
  tmux new-window  -t wat:2 -n logs


  # Window "editor"
  
  tmux send-keys -t wat:0.0 '' C-m
  tmux send-keys -t wat:0.0 vim C-m

  tmux splitw -c /home/peter -t wat:0
  tmux select-layout -t wat:0 main-vertical
  
  tmux send-keys -t wat:0.1 '' C-m
  tmux send-keys -t wat:0.1 guard C-m

  tmux select-layout -t wat:0 main-vertical

  tmux select-pane -t wat:0.0

  # Window "server"
  
  tmux send-keys -t wat:1 bundle\ exec\ rails\ s C-m

  # Window "logs"
  
  tmux send-keys -t wat:2 tail\ -f\ log/development.log C-m

  tmux select-window -t 0
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t wat
else
  tmux -u switch-client -t wat
fi
```

Note: I ran the debugger with my existing .tmux.conf and again with every line removed and still saw this same result.

Please let me know if there's any additional environment or config information I can provide.

**Comment by Soliah** [comment]
Could you try setting the following in your .tmux.conf.

```
set-option -g base-index 1
set-window-option -g pane-base-index 1
```

**Comment by ethagnawl** [comment]
Same results. 

[Here's](https://github.com/ethagnawl/dotfiles/blob/master/.tmux.conf) my .tmux.conf, in case that might be of any help.

**Comment by hori-ryota** [comment]
I don't really why, but I resolved my same type of your issue by removing `eval "$(docker-machine env myContainer)"` from `.zshrc`.

Including `docker-machine env myContainer` command in `.zshrc` for trial, a similar problem occured.

**Comment by podung** [comment]
It looks like commit 16d6c6020cd169a7e4467683d0c9f3c3ad1afc12 on PR #311 fixes all the extra unnecessary calls to send-keys that look like this:

```bash
tmux send-keys -t wat:0.1 '' C-m   # unnecessary call
tmux send-keys -t wat:0.1 guard C-m
```

I think this issue can be closed.

**Comment by ethagnawl** [comment]
I can confirm that after, upgrading to 0.6.11, I'm no longer seeing those unnecessary send-key calls.

**Comment by Soliah** [comment]
Awesome.
