### ISSUE TITLE
Italic font works when tmux started directly but not when started through tmuxinator

### ISSUE THREAD

**Issue by jkrmr** [tmuxinator/tmuxinator#300]
For some reason starting tmux through tmuxinator is disabling italics:

### shell (italics work)
```
~ % echo $SHELL $EDITOR $TERM
/usr/local/bin/zsh vim xterm-256color

~ % vim .tmuxinator/sample.yml
```
![screen shot 2015-05-08 at 5 32 13 am](https://cloud.githubusercontent.com/assets/4433943/7536313/a50d8ff8-f543-11e4-9dbe-d514bdf41fd3.jpg)

### tmux (italics work)
```
~ % echo $SHELL $EDITOR $TERM
/usr/local/bin/zsh vim xterm-256color

~ % vim .tmuxinator/sample.yml
```
![screen shot 2015-05-08 at 5 34 29 am](https://cloud.githubusercontent.com/assets/4433943/7536372/17062ac0-f544-11e4-8734-876ef3326b7f.jpg)

### tmuxinator (italics break)
```
~ % echo $SHELL $EDITOR $TERM
/usr/local/bin/zsh vim xterm-256color

~ % vim .tmuxinator/sample.yml
```
![screen shot 2015-05-08 at 5 37 14 am](https://cloud.githubusercontent.com/assets/4433943/7536408/7af62684-f544-11e4-96c2-98f310da7733.jpg)

**Comment by jkrmr** [comment]
This was caused by having the following alias set in my zsh configuration:

```sh
alias tmux='env TERM=screen-256color tmux'
```

A somewhat hackish solution<sup>1</sup> to the problem of getting italics to work in tmux, discussed [here](https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
) on the Unix & Linux Stack Exchange.

<sup>1. though arguably the lesser of the evils considering the alternative solutions</sup>

Tmuxinator starts tmux using a non-login shell, so it wasn't using the alias.

Moving the alias into `.zshenv`  from `.zshrc` resolves the issue.

**Comment by jkrmr** [comment]
Spoke too soon -- somehow setting the alias in `.zshenv` resolves the issue for the `tmux open` command but not for `tmuxinator start`.

**Comment by Soliah** [comment]
Does setting `set-option -g default-terminal "xterm-256color"` in tmux help?

**Comment by jsatk** [comment]
Is this still an issue? Do I still need the override for tmuxinator?
