### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by Soliah** [tmuxinator/tmuxinator#301]
Would be great if there were a few more people helping out as I haven't been paying as much attention to tmuxinator as I would like. Anyone willing to help out?

**Comment by ethagnawl** [comment]
I'll have a look through the issues, do some triage and pick-up anything I might be able to fix. (As my schedule allows, of course.)

Thanks for all you've done thus far! :+1:

**Comment by Soliah** [comment]
@podung would you be willing to help out?

**Comment by podung** [comment]
@Soliah I'll def consider it.  To be honest, I'm not sure what all that entails.

For now, I'll help crank through some of the existing issues.  Also, I'd like to discuss getting the tmux template and wemux templates merged into one so we don't have to maintain two nearly identical templates.  I'll start a separate issue for that.

**Comment by magicalbanana** [comment]
I can help out if you want.

**Comment by Soliah** [comment]
No obligations at all. I'll add you both as collaborators and you can help where you feel comfortable.
