### ISSUE TITLE
Launching multiple Tmuxinator sessions from a script?

### ISSUE THREAD

**Issue by mahemoff** [tmuxinator/tmuxinator#314]
To start my workflow, e.g. after a reboot, I'd like to do something like this in a bash script:

    tmuxinator project1
    tmuxinator project2
    tmuxinator project3

This only launches them one at a time. Appending & doesn't help. (I see there's an "attach" option in the config. If I could apply "attach: false" on the command line, it could possibly support launching several projects.)

Is there any way to do this?

**Comment by Soliah** [comment]
Starting without attaching should be supported now.

**Comment by mahemoff** [comment]
Thanks
(https://github.com/tmuxinator/tmuxinator/pull/307 for the record)

**Comment by mahemoff** [comment]
I've found this still doesn't work (v7.1). Not sure if it's a tmux issue, but it seems the sessions get "merged" together so the terminal is basically a mess and tmux shortcuts don't work.
