### ISSUE TITLE
Readme doesn't explain what ERB is

### ISSUE THREAD

**Issue by erikb85** [tmuxinator/tmuxinator#317]
> Project files support ERB for reusability across environments

What does that mean? Could you link it to a description of what ERB is or give context to the people who don't need to care about it?

PS: Google yields *Epic Rap Battles*. I guess we don't need to be reusable for them. ;)

**Comment by s3rvac** [comment]
ERB stands for [Embedded Ruby](https://en.wikipedia.org/wiki/ERuby). It is a templating system that allows one to embed Ruby code into a text document.

**Comment by Soliah** [comment]
Should probably give an example in the README.
