### ISSUE TITLE
can't run tmuxinator

### ISSUE THREAD

**Issue by iTeam91** [tmuxinator/tmuxinator#321]
Can't run tmuxinator. Please help me
```terminal```
$ tmuxinator
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'tmuxinator' (>= 0) among 13 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/bin/tmuxinator:22:in `<main>'
```

**Comment by iTeam91** [comment]
I was editing my oh-my-zsh config and i don't know how, but i removed tmuxinator.

**Comment by MacgyverMartins** [comment]
For everyone that came here, the problem probably is your Ruby path
If you are using RVm and install tmuxinator before it, try this;
`rvm use system`, and then, try run tmuxinator again. 

You can set up this Ruby as a default doing this `rvm --default use system`. 
You can also re-install tmuxinator using your current rvm ruby version
