### ISSUE TITLE
Problem with custom layout

### ISSUE THREAD

**Issue by aMoniker** [tmuxinator/tmuxinator#322]
I'm successfully using a less complex custom layout. However, after I add a few panels through tmux (which work fine), then use `tmux list-window` to get the layout and paste it into my tmuxinator config, I get the following:

```
mux my_project
can't set layout: b9e8,270x63,0,0{135x63,0,0[135x31,0,0,0,135x31,0,32,5],134x63,136,0[134x16,136,0{67x16,136,0,1,66x 16,204,0,4},134x23,136,17,2,134x22,136,41,3]}
can't set layout: b9e8,270x63,0,0{135x63,0,0[135x31,0,0,0,135x31,0,32,5],134x63,136,0[134x16,136,0{67x16,136,0,1,66x 16,204,0,4},134x23,136,17,2,134x22,136,41,3]}
can't set layout: b9e8,270x63,0,0{135x63,0,0[135x31,0,0,0,135x31,0,32,5],134x63,136,0[134x16,136,0{67x16,136,0,1,66x 16,204,0,4},134x23,136,17,2,134x22,136,41,3]}
can't set layout: b9e8,270x63,0,0{135x63,0,0[135x31,0,0,0,135x31,0,32,5],134x63,136,0[134x16,136,0{67x16,136,0,1,66x 16,204,0,4},134x23,136,17,2,134x22,136,41,3]}
can't set layout: b9e8,270x63,0,0{135x63,0,0[135x31,0,0,0,135x31,0,32,5],134x63,136,0[134x16,136,0{67x16,136,0,1,66x 16,204,0,4},134x23,136,17,2,134x22,136,41,3]}
** tmux mode started **
```

Could someone else give this layout a shot and let me know if they see the same issue?

**Comment by podung** [comment]
Can you give a little more info?  I'll try to replicate on my end but I'm not sure exactly what you're trying to accomplish.

**Comment by aMoniker** [comment]
Just tried another layout with five panels, but it's dropping one so I only get four:
`layout: 5bff,268x67,0,0{134x67,0,0[134x33,0,0,0,134x33,0,34,4],133x67,135,0[133x17,135,0,1,133x24,135,18,2,133x24,135,43,3]}`

Are you able to get the original layout posted to work?

**Comment by aMoniker** [comment]
Actually... a new layout with six panels based on the original posted is now working. I'm not sure what changed since yesterday.

**Comment by podung** [comment]
Glad it's working for you now.
