### ISSUE TITLE
'mux start' not working: undefined method 'each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by patrickdepinguin** [tmuxinator/tmuxinator#328]
I installed tmuxinator using 'sudo gem install tmuxinator', created a project and then attempted to start it. I get the following failure:

    $ mux start foo
      (erubis:41:in `block in render': undefined method `each' for nil:NilClass (NoMethodError)
            from (erubis:34:in `each'
            from (erubis:34:in `render'
            from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
            from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
            from /var/lib/gems/1.9.1/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:17:in `render'
            from /var/lib/gems/1.9.1/gems/tmuxinator-0.6.11/lib/tmuxinator/cli.rb:77:in `start'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /var/lib/gems/1.9.1/gems/tmuxinator-0.6.11/bin/mux:18:in `<top (required)>'
            from /usr/local/bin/mux:23:in `load'
            from /usr/local/bin/mux:23:in `<main>'
    
    $ tmuxinator version
    tmuxinator 0.6.11
    $ tmuxinator doctor
    Checking if tmux is installed ==> Yes
    Checking if $EDITOR is set ==> Yes
    Checking if $SHELL is set ==> Yes
    $ tmux -V
    tmux 2.0

This is on Linux.
Please let me know which other information I can provide. 
I did not find any similar issues, so there must be something wrong in my installation.

**Comment by magicalbanana** [comment]
It's because you install it with a sudo, so to run the mux you need to:

```
sudo mux
```

But this is not ideal. You should have installed the gem without the sudo. How did you install your rubies? If you did it under su then I recommend rebuilding it again.

**Comment by patrickdepinguin** [comment]
When I tried installing without sudo, I get:

    $ gem install tmuxinator
    Fetching: tmuxinator-0.6.11.gem (100%)
    ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.

Obviously I don't have write access to /var/libs as a regular user. 

Ruby was installed using (sudo) apt-get.
How should I have installed it?
To clarify: I'm absolutely unfamiliar with Ruby/gems.

**Comment by magicalbanana** [comment]
You shouldh have installed it without sudo the least.

Here, not sure what you're trying todo with ruby but installation should be
a breeze with this guide.

https://gorails.com/setup/ubuntu/15.04

On Thu, Aug 6, 2015 at 1:44 PM, Thomas De Schampheleire <
notifications@github.com> wrote:

> When I tried installing without sudo, I get:
>
> $ gem install tmuxinator
> Fetching: tmuxinator-0.6.11.gem (100%)
> ERROR:  While executing gem ... (Gem::FilePermissionError)
> You don't have write permissions into the /var/lib/gems/1.9.1 directory.
>
> Obviously I don't have write access to /var/libs as a regular user.
>
> Ruby was installed using (sudo) apt-get.
> How should I have installed it?
> To clarify: I'm absolutely unfamiliar with Ruby/gems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmuxinator/tmuxinator/issues/328#issuecomment-128471100>
> .
>



-- 

[image: kareemgan] <http://kareemgan.com>

Kareem Gan / Software Engineer
kareemgan@gmail.com

[image: Skype] <https://github.com/magicalbanana> [image: Facebook]
<http://facebook.com/dopankey> [image: Twitter] <http://@kareemgan> [image:
Google Plus] <https://plus.google.com/108299918329354290658> [image:
Linkedin] <https://linkedin.com/in/kareemgan> [image: Skype]
<http://kareemgan>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by patrickdepinguin** [comment]
That guide seems to be to set up a development environment for Ruby. 
In my case, I simply want to use tmuxinator, I'm not planning any Ruby development. 

I found out about the --user-install option to gem, so after uninstalling tmuxinator, thor, erubis from the system, I reinstalled them using 'gem install --user-install foo', but the error is still the same:

    $ mux start kallithea
    (erubis:41:in `block in render': undefined method `each' for nil:NilClass (NoMethodError)
        from (erubis:34:in `each'
        from (erubis:34:in `render'
        from /home/tdescham/.gem/ruby/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /home/tdescham/.gem/ruby/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /home/tdescham/.gem/ruby/1.9.1/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:17:in `render'
        from /home/tdescham/.gem/ruby/1.9.1/gems/tmuxinator-0.6.11/lib/tmuxinator/cli.rb:77:in `start'
        from /home/tdescham/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/tdescham/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tdescham/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/tdescham/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/tdescham/.gem/ruby/1.9.1/gems/tmuxinator-0.6.11/bin/mux:18:in `<top (required)>'
        from /home/tdescham/.gem/ruby/1.9.1/bin/mux:23:in `load'
        from /home/tdescham/.gem/ruby/1.9.1/bin/mux:23:in `<main>'

**Comment by magicalbanana** [comment]
You may not be developing rails but I recommend going through it since the
guide for installing ruby is proven.

**Comment by bbuchalter** [comment]
I got this error when I didn't have `tmux` installed on my Ubuntu machine....maybe same for others? Maybe we need to improve the error handling/message?

**Comment by fikovnik** [comment]
I had the same problem which I fixed by adding

```
@commands = []
```

right after `@panes = []` in `initialise` method in `window.rb`.

If you think it is a bug I can make a pull request.

**Comment by zetetic** [comment]
@fikovnik I experienced the same problem, and it went away after adding your fix in `window.rb`. Definitely seems like a bug.

**Comment by njbraun** [comment]
@fikovnik I ran into the same issue. This fixes it! Thanks!

**Comment by SuperMarioBean** [comment]
hi, all. I think some one has committed a issue to ruby gems about this https://github.com/rubygems/rubygems/issues/1577

**Comment by J3RN** [comment]
@SuperMarioBean I don't believe that is an issue related to that one, but that one certainly does cause me a lot of grief.

Are people still having this issue? Does it happen with the latest version (1.8)?

**Comment by podung** [comment]
Most of the issues listed above sound like yaml formatting/parsing issues.  If anyone is still having the issue, it would help to see the mux yaml file you're trying to run.  We'll close this soon if we don't get any quick  responses and anyone should feel free to submit a new issue if you think you're experiencing something similar. We'll gladly help out if so

**Comment by cwhits** [comment]
I was getting this error if I'd specify a layout but not the panes (even if I wanted them to just be "empty" panes)

Works:
`windows:
  - Stuff:
      layout: main-horizontal
      panes:
          -
          -
`
Doesn't work:
`windows:
  - Stuff:
      layout: main-horizontal
`

**Comment by madAndroid** [comment]
I've been experiencing the exact same issue, add @fikovnik 's fix in https://github.com/tmuxinator/tmuxinator/issues/328#issuecomment-144604126 sorts it out

**Comment by jusw85** [comment]
Doesn't work:

```
windows:
    - activemq:
        root: ~/opt/apache-activemq-5.13.2

```
Works:

```
windows:
    - activemq:
        root: ~/opt/apache-activemq-5.13.2
        panes: pwd # any dummy command
```

**Comment by J3RN** [comment]
@cwhits @jusw85 It sounds like the issue you guys are having is related to not being able to have a window with no panes. Since that seems different from the problem for which this issue was first created, I'm going to create a new issue to discuss this.

**Comment by podung** [comment]
I'm trying to recreate the issue using @jusw85 example yamls above.  

@J3RN were you able to get tmuxinator to blow up in the same way?  My comment on #428 goes more into my confusion from a code perspective.

**Comment by podung** [comment]
@cwhits @madAndroid @jusw85 

Can you all report what version of tmuxinator you were using when you got this error?

**Comment by cwhits** [comment]
Same as @J3RN.

**Comment by aweibell** [comment]
I got this error when I configured 9 panes. By reducing to 8 (removed one of the previous, not the last added), everything worked fine again.

**Comment by adamstrickland** [comment]
@aweibell can you post your non-working project file, please?

**Comment by aweibell** [comment]
Sorry, I mixed windows and panes. The error message appears with 9 windows and not with 8 windows. Here is a project file (renamed from .yml) that leads to the error message on load.
[9windows.txt](https://github.com/tmuxinator/tmuxinator/files/745187/9windows.txt)
