### ISSUE TITLE
send-keys and long rc file

### ISSUE THREAD

**Issue by chadrien** [tmuxinator/tmuxinator#333]
Hi,

I'm having with tmuxinator and my zsh configuration. It took ~2/3 secondes for my zsh to be ready (executing the `~/.zshrc` etc.).

The consequence of this seem to be that the `tmux send-keys` generated by the commands I put in the configuration of my tmuxinator projects does not work. Well they to work but are triggered before the shell is ready therefore the command is not executed.

I've tried to modify the `template.erb` file locally to add some `sleep`s in it and it seem to do the trick.

So is there any way to tell tmuxinator to use a customised `template.erb` file? Or any other simpler way to overcome this issue?

**Comment by leyyinad** [comment]
+1

**Comment by chadrien** [comment]
@leyyinad interesting, I happen to have the same `eval`. I'll give your trick a try

**Comment by chadrien** [comment]
Seems to work. Thanks for the tip @leyyinad :)
