### ISSUE TITLE
Delete multiple projects at once

### ISSUE THREAD

**Issue by J3RN** [tmuxinator/tmuxinator#337]
This is a feature request. I'd love to be able to delete multiple projects with a command like:
```bash
mux delete project1 project2 ...
```

**Comment by magicalbanana** [comment]
Wouldn't it be easier to just go into the folder and do this manually? Would be safer too.

**Comment by J3RN** [comment]
I think "easier" is a matter of opinion here. In your shell, you could do:
```bash
cd ~/.tmuxinator
rm -i project1.yml project2.yml project3.yml
```

Or, with this feature, you could do:
```bash
mux delete project1 project2 ...
```

and get more or less the same result. 

Despite being less typing (unless you use you file browser to open `~/.tmuxinator`, which is a massive pain in OS X, so I have no idea why you would), Tmuxinator already has the `delete` command, so this change would just enhance an existing feature, not adding anything radical.

Actually, it looks like the fact that config YAML files are stored in `~/.tmuxinator` is never explicitly documented, though it is implicitly documented in the README in an example: 
![screen shot 2015-10-07 at 11 30 27](https://cloud.githubusercontent.com/assets/2058614/10342426/0306ba60-6ce7-11e5-9b01-11718ab909a4.png)


### Conceptual stuff that you do not need pay attention to

The main difference here is maintaining a level of abstraction, and a consistent interface. Let's say, for instance, that Tmuxinator were to move it's YAML files to somewhere else (e.g. `/etc/tmuxinator/` - not that you would, but you theoretically could). When that change was made, it would make sense to update the `mux delete` code to delete from `/etc/tmuxinator` (since this feature already exists in Tmuxinator anyhow). Someone who was used to just opening the folder and deleting the files would now not know where all their configs went, but someone who uses the `mux delete` command who not notice any change, and could continue to use the tool exactly as they were before.
