### ISSUE TITLE
Question: Using tmuxinator to open a dynamic number of windows

### ISSUE THREAD

**Issue by kylezeeuwen** [tmuxinator/tmuxinator#341]
Not an issue more of a usage question not covered in the docs.

as asked here (answer there for reputation !!! :) ) : http://stackoverflow.com/questions/32878441/using-tmuxinator-to-open-a-dynamic-number-of-windows

I would like to set up a tmuxinator project to open a dynamic number of tmux windows. In my scenario I would like one window per instance in an AWS Auto Scale Group.

I have a bash function to list the private IP of each server I want to attach to. For example:

    $ prod-ips
    10.X.X.1
    10.X.X.2
    10.X.X.3
    10.X.X.4

I have a bash function to tunnel to any of those IPs:

    $tunnel_to 10.X.X.1
    ....
    works
    ec2-user@10.x.x.1 ~ $

How do I pass the IP list returned from `prod-ips` into a tmuxinator project so that it will open 1 window for each line of output ?

Thanks!

**Comment by ethagnawl** [comment]
Have you tried doing something like this?

```
# ~/.tmuxinator/dyn.yml

name: dyn
root: ~/
windows:
  <%- `echo "111,222,333"`.split(',').each do |ip| %>
  - tunnel-to-<%= ip.chomp %>: echo tunnel_to <%= ip %>
  <%- end %>

```

![2015-11-01-235053_1600x900_scrot](https://cloud.githubusercontent.com/assets/289949/10874491/69b595e0-80f3-11e5-8705-6b44a3ab1751.png)

**Comment by ethagnawl** [comment]
@kylezeeuwen has marked this as resolved via [StackOverflow](http://stackoverflow.com/q/32878441/382982).
