### ISSUE TITLE
_tmuxinator:2: command not found: tmuxinator

### ISSUE THREAD

**Issue by WhiskeyTuesday** [tmuxinator/tmuxinator#345]
When I open a new terminal I get
`_tmuxinator:2: command not found: tmuxinator`
`_tmuxinator:3: command not found: tmuxinator`
printed at the top.

I'm running:
Terminator
Debian Jesse (Actually Crunchbang ++)
RVM
Standard ruby 2.2.1
ZSH

This occurs whether I have a tmuxinator project in the list or not. if I comment out the line in my zshrc that sources the completion script it goes away.

**Comment by blainekasten** [comment]
I'm getting this also. It happened to me after updating to OS X El Capitan

**Comment by blainekasten** [comment]
Reinstalling worked for me. Did you try that @WhiskeyTuesday ? `gem install tmuxinator`

**Comment by iasj** [comment]
Not working for me too. Even after reinstall.

**Comment by iasj** [comment]
Forget it. I just made my own initializer [IniTmux](https://gitlab.com/iasj/IniTmux).

**Comment by eliasbagley** [comment]
This is happening to me too. Tmuxinator is installed, and reinstalling isn't working for me.

**Comment by magicalbanana** [comment]
Through El Kapitan? Can you tell me what ruby versioning system you guys are using? Because there's an issue with El Kapitan and rbenv.

**Comment by hetre85** [comment]
Happening for me too:

Yosemite
RVM
zsh
iTerm2

Tried `gem uninstall` and a subsequent reinstall of the gem.

I am still able to use `tmuxinator [project]`, I am just receiving the message `_tmuxinator:2: command not found: tmuxinator` when I start iterm2.

**Comment by Soliah** [comment]
This looks like an issue with completions. Are people using zsh-completions?

**Comment by WhiskeyTuesday** [comment]
I'm using Prezto, which I believe includes zsh-completions

**Comment by eliasbagley** [comment]
Unless it's zsh-completions is being included in some other way, I don't think I'm using it. I don't have it listed in my .oh-my-zsh plugins folder.

**Comment by hetre85** [comment]
I'm using oh-my-zsh but I am not using zsh-completions.

**Comment by kfrz** [comment]
I'm also getting  `_tmuxinator:2: command not found tmuxinator` and `_tmuxinator:3: command not found: tmuxinator`. Running: 

El Capitan
RVM (ruby 2.0.0)
oh-my-zsh 
iterm2

**Comment by zkilgore** [comment]
Getting the same thing with nearly the same setup as @kfrz 

El Capitan
RVM (ruby-2.1.1)
zsh + prezto
iterm2

**Comment by crittelmeyer** [comment]
I'm getting something perhaps related, trying to install tmuxinator for the first time on this machine:

```
~  sudo gem install tmuxinator
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/mux
```

**Comment by kfrz** [comment]
Seems like a permissions error to me


- Keifer Furzland

On Sat, Dec 26, 2015 at 5:11 PM, Chris Rittelmeyer <notifications@github.com

**Comment by adamstrickland** [comment]
I agree w/ @kfrz, it looks permissions-related.  If you're on OSX and are using the system ruby (i.e. that which comes with the operating system), IIRC the gem directory is owned by `root`, so you need to install gems using `sudo`:  `sudo gem install tmuxinator`.

**Comment by kfrz** [comment]
Better yet use RVM to manage rubies

**Comment by adamstrickland** [comment]
:+1: agreed

**Comment by zkilgore** [comment]
@adamstrickland @kfrz I just fixed this by ensuring that any sourcing of rvm scripts/variables occurs before I source tmuxinator completions. Thanks for your help!

**Comment by ralfschimmel** [comment]
Indeed @zkilgore adding this to your .bashrc or .zshrc seems to fix it;

`source $HOME/.rvm/scripts/rvm`

**Comment by cinaeco** [comment]
I think the error can also be avoided if we placed tmuxinator.zsh in zsh's `fpath` instead of sourcing it directly, since that seems to be the proper way to add completions to zsh. If you put `fpath=(somedotfilepath $fpath)` in your zshrc, and then `mv tmuxinator.zsh somedotfilepath/_tmuxinator`, it shouldn't matter when you run the rvm initialisation script.

**Comment by J3RN** [comment]
Has this issue been resolved? Is anyone still having trouble with this?

**Comment by hetre85** [comment]
@J3RN ,

Placing `source $HOME/.rvm/scripts/rvm` in my .zshrc, as mentioned by @ralfschimmel and @zkilgore, has resolved the issue for me.

**Comment by J3RN** [comment]
Alright, I'm going to close this. Anyone can feel free to reopen it if they still have issues.

**Comment by rajeshisnepali** [comment]
For me, everything looked perfect. But still had the issue.
```
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes
```
What I did wrong was installing `tmuxinator` without `sudo`. 
So after running `sudo gem install tmuxinator` went all good.

**Comment by tarikwaleed** [comment]
this happend for me when i installed ruby using rbenv.
i did
` apt purge tmuxinator` then,

`gem install tmuxinator`

and It worked for me
