### ISSUE TITLE
Editing project recreates it

### ISSUE THREAD

**Issue by assembler** [tmuxinator/tmuxinator#354]
When I run `tmuxinator edit projectname` it recreates the project yml file with the default one.

I believe the bug is on this line:

https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/cli.rb#L75

^the function expects project name, not the path.

**Comment by adamstrickland** [comment]
So you're saying the observed behavior is that there exists a project YAML definition, and if you run the `edit` command, the existing one is clobbered and replaced with one from the template, is that correct?  In this scenario, where is the project YAML definition, in `~/.tmuxinator/#{project_name).yml` or in `/path/to/project/.tmuxinator.yml`?

**Comment by assembler** [comment]
Yes, that is correct. YML definition is in `~/.tmuxinator/#{project_name).yml`

**Comment by assembler** [comment]
This applies only to latest version. I've downgraded and it works ok.

**Comment by Takif** [comment]
Same problem here.
version 0.7.0

**Comment by joshuakarjala** [comment]
Also have this problem

**Comment by dasilvacontin** [comment]
Same problem here, 0.7.0.

**Comment by hafizio** [comment]
I'm also facing the same problem
