### ISSUE TITLE
mux new <name> erase existing project

### ISSUE THREAD

**Issue by nicolas33** [tmuxinator/tmuxinator#355]
It's unexpected to erase existing projects. It should give an error or fallback to edit mode.
v0.7.0

**Comment by ethagnawl** [comment]
I can also confirm that this broke when upgrading from 0.6.11 to 0.7.0.

**Comment by ethagnawl** [comment]
Should be resolved by fix for #354.

**Comment by adamstrickland** [comment]
Closing as duplicate of https://github.com/tmuxinator/tmuxinator/issues/354
