### ISSUE TITLE
appropriate completion file?

### ISSUE THREAD

**Issue by bkcummins** [tmuxinator/tmuxinator#368]
What is meant by "Download the appropriate completion file"?

How do you know which is appropriate and/or what this does?

Sorry if this is a dumb question...new to tmux and tmuxinator.  Thx!

**Comment by Soliah** [comment]
The required completions file depends on the shell that you're using. They're located here https://github.com/tmuxinator/tmuxinator/tree/master/completion and will need to be sourced in your relevant rc file eg `.bashrc`.

If you use zsh, https://github.com/zsh-users/zsh-completions includes the same completions as above but with a bunch of others too.
