### ISSUE TITLE
setting window specific options / making window names permanent

### ISSUE THREAD

**Issue by vapniks** [tmuxinator/tmuxinator#369]
For some of my windows I use the `cd` command on startup which has the effect of changing the window name. I want to keep the window name permanent for some windows but not for others. This can be acheived in tmux by setting the `automatic-rename` and `allow-rename` options to `off`
How can I do this with tmuxinator?
I have tried putting this in the tmuxinator config: 
```
tmux_options: set-window-option -t 3 automatic-rename off
```
but I get the following error:
```
usage: set-window-option [-agoqu] [-t target-window] option [value]
```
and in any case that only allows me to set one of the windows.

**Comment by podung** [comment]
If this is still an issue for you, can you provide a sample yaml.  I can't recreate your issue.  Perhaps I'm misunderstanding it.

**Comment by vapniks** [comment]
No longer using tmuxinator (using tmux-resurrect instead), so no longer an issue.
