### ISSUE TITLE
A slow-starting shell causes startup commands to never happen

### ISSUE THREAD

**Issue by nfirvine** [tmuxinator/tmuxinator#371]
I'm running zsh loading a prezto and a bunch of crap that causes start-to-prompt time to be about 1 second. This delay is enough to swallow the send-keys input that tmuxinator sends, so nothing ends up happening.

Not sure what can be done about this though

**Comment by christophermanning** [comment]
Ideally, tmux would wait for the prompt to be ready before sending keys.

There may be a better way to wait for the prompt to be ready, but adding sleep before the tmux command in your yml config is a brute force way to fix it: `tmux_command: sleep 1 && tmux`

**Comment by nfirvine** [comment]
Okay, good enough.
