### ISSUE TITLE
Define startup_pane?

### ISSUE THREAD

**Issue by AlexZeitler** [tmuxinator/tmuxinator#380]
Is it possible to define the startup pane? (I know I can define the ```startup_window```)

**Comment by cescoferraro** [comment]
+1

**Comment by podung** [comment]
+1

**Comment by fabianschwarzfritz** [comment]
Oh, those small fixups on the same branch look quite ugly here in the PR overview. Sorry! 😞 

I did a few fixups when I had the PR opened, but not sent yet. I didn't expect fixups to be listed here. Sorry again for adding a lot of stuff here. Feedback on the implementation very appreciated 😄 💭
