### ISSUE TITLE
CHANGELOG and Releases

### ISSUE THREAD

**Issue by J3RN** [tmuxinator/tmuxinator#389]
The `CHANGELOG` file is a bit out of date. If no one objects, I'd like to add updating the `CHANGELOG` to the `CONTRIBUTING` document, and suggest that contributors update the `CHANGELOG` when they submit a pull-request. I'd be happy to go back and add the things that have changed in the last few releases, as well as add that note to the `CONTRIBUTING` document, but I wanted to open this issue as a formal indication of that intent.

Speaking of which, we're also missing some "Releases" here on GitHub. I also plan to go back and git-tag the last few version bumps so that the become formal "releases."

If anyone has any objections to these intentions or would like to help, I'd love to hear about it!

**Comment by adamstrickland** [comment]
:+1: in particular re: updating `CONTRIBUTING` guidelines

**Comment by J3RN** [comment]
This has been instated. Closing.
