### ISSUE TITLE
Standardize use of `say` in Tmuxinator::Cli

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#392]
Currently, `Tmuxinator::Cli` uses both `puts` and [Thor's `say`](http://www.rubydoc.info/github/wycats/thor/Thor%2FShell%2FBasic%3Asay). `say` is a wrapper around `puts` in most scenarios (see docs), but it also offers additional behavior (e.g. an optional `color` argument) and I'd argue that we should use it instead of `puts` throughout, if only for consistency's sake.

**Comment by adamstrickland** [comment]
+1

**Comment by J3RN** [comment]
I agree. Honestly, having color support makes this superior to `puts` for me, since I enjoy having output clearly colored to indicate severity/importance/etc.

**Comment by ethagnawl** [comment]
Closed via #393.
