### ISSUE TITLE
'mux' symlink incorrectly installed on Ruby 2.3.0 (RubyGems issue)

### ISSUE THREAD

**Issue by e2** [tmuxinator/tmuxinator#401]
FYI: https://github.com/rubygems/rubygems/issues/1577

**Comment by ohcibi** [comment]
I have ruby 2.2.3 and the same issue.

**Comment by e2** [comment]
The workaround is to just copy the file until the symlinking is fixed.

It's better to have a gem with duplicate files (no matter how "wrong" that feels) rather than a non-working gem.

**Comment by J3RN** [comment]
Something I have been contemplating is removing the `mux` file altogether, and just suggesting that people alias `mux` to `tmuxinator`.

**Comment by ethagnawl** [comment]
@J3RN @ncoop Shall we close this issue?

**Comment by J3RN** [comment]
Since this is a RubyGems issue and the issue has been appropriately opened on that repo, I will close this issue.

**Comment by ncoop** [comment]
Out of curiosity, how have other gem maintainers dealt with this?

**Comment by J3RN** [comment]
@ncoop Hard to say, but we're the only ones who have referenced the RubyGems issue.
