### ISSUE TITLE
Completion issue

### ISSUE THREAD

**Issue by synthmeat** [tmuxinator/tmuxinator#405]
As of 0.8.0, completion started appending ` ,` to all layouts.

```tmuxinator start project ,```

That also obviously fails to start it, since it's not defined as such.
Completing for all layouts (`tmuxinator start <Tab>`) gives out:
```
[actionhero,                                          kation,                                               source/spec/fixtures/detach,                          source/spec/fixtures/sample.deprecations,
aura,                                                 newton,                                               source/spec/fixtures/nameless_window,                 source/spec/fixtures/sample_literals_as_window_name,
company,                                              personal,                                             source/spec/fixtures/noname,                          source/spec/fixtures/sample_number_as_name,
golive,                                               showdown,                                             source/spec/fixtures/nowindows,                       source/spec/fixtures/sample_wemux]
joyplane,                                             source/lib/tmuxinator/assets/sample,                  source/spec/fixtures/sample,                          
```

Ruby 2.2.

**Comment by J3RN** [comment]
Geez, that's bizarre! Thanks for reporting it. What shell are you using? I'm assuming that you're sourcing the completions file for your shell?

**Comment by synthmeat** [comment]
bash, and yes, sourced as usual (haven't changed it, just did update on tmuxinator).

Thought it might be related to `bash-completion`, but it seems to work ok otherwise (i.e., ssh hosts from `~/.ssh/config` get completed properly.

**Comment by J3RN** [comment]
It looks like there's a similar issue in ZSH, but it looks like this:
<img width="1280" alt="screen shot 2016-04-13 at 14 43 16" src="https://cloud.githubusercontent.com/assets/2058614/14505202/232fa944-0186-11e6-9b6a-ce7df5aa9e3d.png">

I'll start digging on this.

**Comment by synthmeat** [comment]
I actually *did* have unupdated tmuxinator source in my dotfiles, which is where I source completion but, alas, the issue remained.

**Comment by kelvinst** [comment]
Oh gosh, I would comment if you have any news. Now I saw that this issue was reported yesterday. lol

**Comment by gibbling** [comment]
Same for fish shell

<img width="167" alt="screen shot 2016-04-15 at 12 43 30 pm" src="https://cloud.githubusercontent.com/assets/6933314/14568562/b4abd186-0307-11e6-82b3-d4cb59e660a6.png">

**Comment by kelvinst** [comment]
I've just checked. On 0.7.0 version of the gem it works perfectly (even with the new version of the completion script). Something changed on the `tmuxinator projects` command:

```bash
$ /Users/kelvinst/.rvm/gems/ruby-2.3.0/gems/tmuxinator-0.7.0/bin/tmuxinator completions start
default
dotfiles
jmseg-risk-control3
minestore-walmart
minestore
risk-control
sherclock

$ /Users/kelvinst/.rvm/gems/ruby-2.3.0/gems/tmuxinator-0.8.0/bin/tmuxinator completions start
["default", "dotfiles", "jmseg-risk-control3", "minestore-walmart", "minestore", "risk-control", "sherclock"]

```

**Comment by kelvinst** [comment]
I'll make a `git bisect` to check this tonight, so we can identify which commit broke it. :)

Maybe I could even fix, add a test and PR you if I get some time tonight.

**Comment by J3RN** [comment]
It looks like the issue is the line `lib/tmuxinator/cli.rb:58`:
```ruby
say configs
```

It should be something like:
```ruby
say configs.join("\n")
```

I'll look through the history to see why it was changed, and probably make a PR.

**Comment by kelvinst** [comment]
Any idea of when you release this fix on a gem version? :grin:

**Comment by J3RN** [comment]
@kelvinst The pull request is in the works, I'd just like to write a test before releasing so it doesn't happen again! With any luck, later today.

**Comment by J3RN** [comment]
Sorry to ping you guys on a closed issue, but now is the time to run `gem update tmuxinator`. Happy tmuxing!

**Comment by kelvinst** [comment]
🎉 🎆 THANKS! Updated and running.. :)
