### ISSUE TITLE
Expand arguments before shellescape

### ISSUE THREAD

**Issue by mjsr** [tmuxinator/tmuxinator#409]
Using <%= @args[0] %> in a command causes a shellescape error.

The arguments should be expanded before trying to shellescape the provided string in the YAML configuration file.

**Comment by J3RN** [comment]
Hey @mjsr! To help me replicate this error, could you please post as much of the YAML file as you can, and check your Tmuxinator version? You should be able to check that with `mux -v`.

**Comment by mjsr** [comment]
@J3RN, I cannot repro this issue anymore. Probably a mistake on my end.

Things are working as expected now. Sorry for the trouble and thanks for getting back to me.

- mjsr
