### ISSUE TITLE
Root is ignored on tmux 2.2: all windows and panes use /

### ISSUE THREAD

**Issue by razor-x** [tmuxinator/tmuxinator#421]
Given a profile like

```
name: default
root: ~/

windows:
  - main: ls
```

All panes will start in `/` and not `~/`.

I get the expected behaviour on tmux 2.1, and the bad behaviour on tmux 2.2.

Running on Arch Linux: 4.5.4-1-ARCH x86_64 GNU/Linux.

**Comment by J3RN** [comment]
@razor-x Thanks for reporting this! It looks like this issue is a duplicate of #410. Let's move this discussion over there.

**Comment by nicolas33** [comment]
This is not a duplicate, IMHO. root variable is ignored for both relative and absolute paths with tmux 2.2.

**Comment by nicolas33** [comment]
Notice I have to add `-c "$PWD"` to my manual "tmux new-session" invokations to get tmux not starting in my home `~`.
