### ISSUE TITLE
Introduce Analytics Module

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#427]
Per [#426](https://github.com/tmuxinator/tmuxinator/pull/426#issuecomment-223695238), I'd like to start a conversation about introducing an opt-in analytics module.

Open questions:
1. how will data be communicated/persisted? (e.g. Net::HTTP => Firebase)
2. how will the opt-in feature fit into to the Gem installation workflow?
3. what information should be captured? (e.g. Tmux version, OS, OS version, misc. usage, etc.)

**Comment by J3RN** [comment]
Here's my two cents:

1. I've never had fun with Net:HTTP. I'd lean towards [httparty](https://github.com/jnunemaker/httparty)  or [faraday](https://github.com/lostisland/faraday), but that's only my opinion.
2. Could we do this with a post-install trigger?
3. Tmux version and OS are a must. Naturally, the Tmuxinator version should be reported. I'm thinking that a request should be fired off whenever a user runs a certain command (mux start?) and should probably be run async so as to not cause a noticeable performance hit.

**Comment by ethagnawl** [comment]
> I've never had fun with Net:HTTP. I'd lean towards httparty or faraday, but that's only my opinion.

Generally speaking, I agree. However, I'd prefer to avoid introducing a new dependency and Net::HTTP should be tolerable if we're only making a single or very few, similar requests.

> Could we do this with a post-install trigger?

Right - that's what I was thinking. However, after a (brief) look through the Gemspec docs, I don't see any mention of post-install hooks/triggers - just the infamous `post_install_message`.

The quick-and-dirty approach would be to have the gem prompt the user the first time it's run and then write their decision out to a file, which it'd reference in the future.

> I'm thinking that a request should be fired off whenever a user runs a certain command (mux start?) and should probably be run async so as to not cause a noticeable performance hit.

This is the one aspect of this feature I'm unsure about. It'd be nice to know which commands people are using, but I'm not entirely sure what's to be gained from that data.

I was thinking it might be good to start with a single request that's triggered post-install (which attempts to collect Tmux version, Tmuxinator version, OS, etc.) to see if people are even interested in sharing this data.

**Comment by podung** [comment]
How about an opt-out instead?

I'm concerned about how many users would go out of their way to opt-in and question the value if we only get data from a small fraction of our user base.

An obvious, informative post-install message and frictionless opt-out seems like a reasonable approach (something like `mux optout`).  

I bounced the idea around with some coworkers (all tmuxinator users) and they all thought opt-out is totally reasonable if the messaging is clear.

Thoughts?  Would this be perceived as too obtrusive or invasive?

**Comment by Soliah** [comment]
@podung EmberCLI and other projects have a prompt on initial run via https://github.com/yeoman/insight which I think is quite nice. It's also quite nice how they're just piggy backing off of Google Analytics.

![](https://raw.githubusercontent.com/yeoman/insight/master/screenshot-askpermission.png)

In terms of storing a user's decision on disk, perhaps that would be better if #360 is done so we don't add another file to the home directory.

**Comment by podung** [comment]
@Soliah Yeah I agree that looks nice.  Sounds good to me.  Just wanted to make sure we at least discussed the options.

**Comment by ethagnawl** [comment]
Thanks for the feedback, all!

Based on the above, I'm thinking the first pass should look something like the following:

- Use Net::HTTP to send environment info (OS, OS version, Tmux version, Tmuxinator version, anything else?) to Google Analytics
- Ask users to opt-into sharing anonymous data using a pre-populated "Yes" response - assuming Thor supports some form of this
- Store the user's preference on disk (if possible, wait until XDG support has been added in order to prevent further pollution of their home directories)

Remaining open questions:

- Should we create a Tmuxinator Google account?
- Are people okay with collecting only the user's environment information in the first iteration? Before littering the codebase with logging code to track usage, we'll probably want to be sure that 1) users are willing to opt-in and 2) data generated by tracking activity is useful.

**Comment by adamstrickland** [comment]
:-/

I'd say: 
- Use Net::HTTP -> Google Analytics
- Ask users to opt out as part of install process
- For the time being, do not save preferences
- Yes, we create a G Analytics account for storage of same
- Env info (only) is fine for the first pass

For that last bullet point, we don't (yet) have a defined use case for capturing runtime analytics, therefore YAGNI...

**Comment by adamstrickland** [comment]
Fwiw I personally prefer faraday to Net::HTTP, but that's a minor quibble IMO

**Comment by ethagnawl** [comment]
@adamstrickland Why the long face? 

> For the time being, do not save preferences

Are you thinking the environment info should be reported every time the gem is used? I was originally thinking the data would be reported once (post-install) but now you've got me rethinking otherwise... For instance, the one-time approach wouldn't tell us when people upgrade Tmux.

**Comment by ethagnawl** [comment]
Another, simpler approach could be asking users to fill out an online survey as part of the Ruby Gems `post_install_message`, a la Cucumber. 

![screenshot 2016-08-15 17 21 22](https://cloud.githubusercontent.com/assets/289949/17680298/7e2366cc-630d-11e6-88df-e2a2d4fafba2.png)

**Comment by ethagnawl** [comment]
[Here's](https://pdoherty.typeform.com/to/BGDIfM) a first pass at the online survey.

Does anyone have any feedback about this approach or the questions themselves?

**Comment by HaleTom** [comment]
@ethagnawl Perhaps define regularly? Otherwise, LTGM.

I answered "no" to would I opt-in, because of a lack of trust, due to a lack of information about the trustworthiness of the reporting tool / implementation. It's an emotional FUD response.

I suspect that providing a FUD-reducing tinyURL where users can find out more would more than double your opt-in rate.

**Comment by ethagnawl** [comment]
@HaleTom Thanks for the feedback! I'll incorporate the above in my next pass at this.

**Comment by ncoop** [comment]
I think everyone here is getting too wrapped up in the implementation to question the motivation.

The problem is you want to know when to drop support for old versions of tmux. The answer is "whenever you want". Having all the data isn't going to make maintaining old tmux support, or cutting off old tmux users any easier.

Just maintain a tmux-tmuxinator version compatibility table in the README, and users will know what to do. Usage analytics is a feature that shouldn't exist.

**Comment by ethagnawl** [comment]
Closing this for now. Please re-open if anyone thinks it's worth discussing.
