### ISSUE TITLE
ActiveSupport 5.0 breaks build for Ruby < 2.2.3

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#432]
This dependency appears to be coming from factory_girl. 

I took a quick pass at addressing this and at appears that locking ActiveSupport at < 5.0.0 in Tmuxinator's Gemfile solves the problem ([gist](https://gist.github.com/ethagnawl/baa517a8537424532815e75bea436037)).

**Comment by adamstrickland** [comment]
So, do we want to 🚢  this and then have https://github.com/tmuxinator/tmuxinator/pull/416 pull latest before merging in the PR?

**Comment by adamstrickland** [comment]
As an aside, why are we putting this in the Dockerfile and not in the Gemfile itself?

**Comment by ethagnawl** [comment]
> So, do we want to :ship: this and then have #416 pull latest before merging in the PR?

That sounds good by me.

> As an aside, why are we putting this in the Dockerfile and not in the Gemfile itself?

That was just me reproducing the broken build. The change in the [PR](https://github.com/tmuxinator/tmuxinator/pull/433/files) was made to the Gemfile.

**Comment by adamstrickland** [comment]
Ah cool 👍
