### ISSUE TITLE
Command to create local .tmuxinator.yml

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#437]
It'd be nice to be able to create a local tmuxinator project via the CLI. 

I'm open to suggestions as to the best way to approach this, but my first instinct is to piggyback off of `tmuxinator new` and create a local .tmuxinator.yml if no name parameter is provided. We could also introduce a Y/N prompt to ensure that this is what the user really wants to do. I also wouldn't be opposed to adding similar behavior to `tmuxinator local`.

**Comment by adamstrickland** [comment]
I kinda prefer the `tmuxinator new ${name} --local` approach.

**Comment by ethagnawl** [comment]
@adamstrickland Sure, I wouldn't be opposed to that. Maybe we also add an optional `--local` flag to `tmuxinator start`, too.

**Comment by adamstrickland** [comment]
Agreed; we should at least be consistent.

**Comment by ethagnawl** [comment]
I just took a more thorough look into this "issue" and discovered that it's already possible to create a local tmuxinator project using the command @adamstrickland mentioned above. (My apologies, I didn't realize you were saying you preferred the behavior _as it exists_.)

There is, arguably, a communication problem here, though. The docs don't mention this feature and because `tmuxinator help` doesn't mention command options, users need to drill down into `tmuxinator help new` in order to find out that this option exists. Unfortunately, I don't think we can do anything about the latter.

For simplicity's sake, I'm going to close this issue and open a new one about updating the documentation.
