### ISSUE TITLE
How to give focus to a particular pane/window

### ISSUE THREAD

**Issue by emayssat-ms** [tmuxinator/tmuxinator#455]
I can create tmux sessions with multiple multiple windows and multiple panes.
But how can I set the default windows to be the 2nd one, and the pane with focus on each windows to be the one I want (at 'tmuxinator start' of course).
I assume those are tmux commands, but could not find anything there related to focus.

Please help,

**Comment by emayssat-ms** [comment]
tmux select-window ...
tmux select-pane ...

**Comment by emayssat-ms** [comment]
Well, it seems you just have to use a 'sleep 2' as the first command!

**Comment by bbugyi200** [comment]
To specify the startup window, you can use the `startup_window` option (check the README). I couldn't find a analagous option for selecting a startup pane on each window; however, I think you might want to adjust your workaround to use just `tmux select-pane -t [W].[P]`, where `W` is the window number and `P` is the pane number of whichever pane you want to focus on window `W`. This seems to be working well for me.

**Comment by rightaway** [comment]
Are maintainers interested in this feature? Something like `focus: true` under the pane object?

**Comment by ethagnawl** [comment]
There's already an option to apply focus to one particular pane in the `startup_window` (which is either specified or set by default). 

For instance:
```
project_name: focus
startup_window: 1
startup_pane: 1
...
```

This should be in the sample.yml in the README, so I will create an issue to track adding it.

I'm going to close this issue for now, but please feel free to re-open if anyone thinks there's anything else worth discussing.
