### ISSUE TITLE
Can tmuxinator automatically save the session config to the .yml file instead of editing by hand?

### ISSUE THREAD

**Issue by DeathPoem** [tmuxinator/tmuxinator#456]
I'm now here, and wondering can I make tmuxinator save the state of tmux session and write these state to the .yml config file? If not, are we going to do this?

**Comment by ethagnawl** [comment]
There's [a pending pull request](https://github.com/tmuxinator/tmuxinator/pull/426) which purports to implement this feature. 

If you're feeling up to it, I'm sure the folks involved in that PR would appreciate some additional QA.
