### ISSUE TITLE
Remove Object#blank? monkey patch

### ISSUE THREAD

**Issue by ethagnawl** [tmuxinator/tmuxinator#458]
`Object#blank?` is currently being monkey-patched in Tmuxinator.rb. 

However, the project has a dependency on Active Support (see #432), which is where the source of this monkey patch originates. So, as long as the project maintains that dependency, the monkey patch in Tmuxinator.rb isn't necessary.

**Comment by Soliah** [comment]
ActiveSupport was removed in #199 as it seemed unnecessary. That PR also added the monkey patch I believe. If factory_girl was pulling it in as a dep it should've been limited to a development dependency.

**Comment by J3RN** [comment]
Whoa, I just realized that there's gems in our Gemfile. We should probably remove those.

**Comment by ethagnawl** [comment]
Closing this in favor of #459.

**Comment by J3RN** [comment]
To be fair, I think we should still remove the monkey patch. A quick `ag` says that `blank?` is only used twice. I'd have to do a bit of digging, but I suspect it probably wouldn't be too hard to change those two instances.

**Comment by Soliah** [comment]
@ethagnawl Just thought I'd add that ActiveSupport isn't a runtime dep, so though factory_girl is included via bundler, it's not required during install of the gem.
