### ISSUE TITLE
Remove Gems from Gemfile

### ISSUE THREAD

**Issue by J3RN** [tmuxinator/tmuxinator#459]
I can't find the documentation on this, but I believe it's an antipattern to have dependencies listed in a gem's Gemfile. As meager evidence of this, I included a screenshot of the default Gemfile when creating a new gem:
![screen shot 2016-09-23 at 10 37 54 am](https://cloud.githubusercontent.com/assets/2058614/18789759/2447da12-817a-11e6-9997-66ea7dde307d.png)

If I'm right about this, we should remove the gems listed in our Gemfile.

**Comment by adamstrickland** [comment]
I think the original intent (just speculating here, based on the gems enumerated) was to keep development/testing/tooling dependencies in the the Gemfile, and keep the runtime dependencies in the gemspec.  That being said, there's no reason why we couldn't move the Gemfile deps to the gemspec as `#add_development_dependency` line items.

**Comment by ethagnawl** [comment]
@J3RN, I think you are right. I was actually reading [this](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) blog post just now, which makes that case.

**Comment by Soliah** [comment]
@adamstrickland Looks like it was me merging #311. Originally I did have the development deps in the gemspec but looks like I must of missed the change in the that PR.
