### ISSUE TITLE
Replace screenshot with a gif in readme

### ISSUE THREAD

**Issue by Soliah** [tmuxinator/tmuxinator#460]
Would be nice if it wasn't just the screenshot and a gif that illustrated tmuxinator in action :)

**Comment by J3RN** [comment]
I actually made one for a work presentation recently. I'll make a new one that doesn't have trade secrets and put it in a PR tomorrow 😄

**Comment by ethagnawl** [comment]
![output](https://user-images.githubusercontent.com/289949/44366875-1a6cee00-a49c-11e8-9322-76e70df0c88b.gif)
