### ISSUE TITLE
tmuxinator config files in a different location

### ISSUE THREAD

**Issue by emayssat-ms** [tmuxinator/tmuxinator#462]
I would like to be able to change the location of the tmuxinator file
For example 
tmuxinator list --directory /tmp/tmuxinator 
should report the projects in /tmp/tmuxinator instead of ~/.tmuxinator

is something similar possible?

**Comment by ethagnawl** [comment]
@emayssat-ms This is not currently possible. 

However, this feature could potentially be added in conjunction with #360.

**Comment by ethagnawl** [comment]
@emayssat-ms This should now be possible on master via #511. This feature has not yet made it into a release of the gem, though.
