### ISSUE TITLE
Is there a way to enter a command, but just wait for enter?

### ISSUE THREAD

**Issue by emayssat-ms** [tmuxinator/tmuxinator#469]
I would like to enter a command in a pane, but I don't want it to be executed. In other words, the user will have to go to the correct pane and press enter to send the command. Is this possible? If so how?

**Comment by adamstrickland** [comment]
As far as I know, this isn't possible.  Tmuxinator uses ruby to send commands to the operating system; the process of sending the commands by nature executes them.  After doing a little bit of [googling](https://goo.gl/EJ3K0C) I found some cases where people want to do something similar within the shell itself.  According to [this](https://stackoverflow.com/questions/19115156/show-commands-without-executing-them), it would appear that the shell doesn't support this, either.

**Comment by adamstrickland** [comment]
I'm going to close this issue for now.  If you find additional information that requires a change to tmuxinator itself, please re-open.

**Comment by ethagnawl** [comment]
@emayssat-ms A workaround would be prefix the command with a comment, recall the last command (up key in Bash), delete the comment and press enter.

**Comment by wkentaro** [comment]
I also hope this feature, but currently I'm using `read &&` prefix like `read && cat log.txt`.

**Comment by emayssat-ms** [comment]
I have found another way.... through the history.
history -s <command>

Then just use up arrow to execute!
