### ISSUE TITLE
tmuxinator and tmuxinator local 

### ISSUE THREAD

**Issue by emayssat-ms** [tmuxinator/tmuxinator#472]
to my surprice tmuxinator by itself on the command line finds the .tmuxinator.yml and runs it!
this behavior is not documented and therefore was not expected.

**Comment by Soliah** [comment]
Documented here: https://github.com/tmuxinator/tmuxinator#starting-a-session

If you would like to make it more obvious feel free to submit a PR for the readme.

**Comment by emayssat-ms** [comment]
I don't see where it says: 'tmuxinator' by iteslf will start a project. Based on the section you  are pointing to, it seems that tmuxinator start project ... will start the local project (which I believe is still not since I believe one should type 'tmuxinator local') Oh, well...
