### ISSUE TITLE
tmuxinator start project --windows window1 (or --panes window1.pane1) (or --windows window1,window2)

### ISSUE THREAD

**Issue by emayssat-ms** [tmuxinator/tmuxinator#475]
To debug complex tmuxinator session (I have one with 20 panes with different commands), it would be useful to be able to start only a specific window of the project, or even just a pane based on names. This feature is useful if you are debugging the command entered.

**Comment by emayssat-ms** [comment]
http://stackoverflow.com/questions/23166031/tmux-why-do-these-two-lines-cause-a-tmux-conf2-cant-establish-current-sess

**Comment by ethagnawl** [comment]
@emayssat-ms Similar behavior can be achieved using ERB conditionals and optargs.
