### ISSUE TITLE
gem install tmuxinator fails on MSYS2 for versions 0.7.2 and above

### ISSUE THREAD

**Issue by smani** [tmuxinator/tmuxinator#490]
`gem install -v 0.7.2 tmuxinator` fails on MSYS2. The versions `0.7.0` and `0.7.1` works for me.

### `0.7.2` error

    ERROR:  While executing gem ... (Errno::ENOENT)
        No such file or directory @ rb_file_s_symlink - (/c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.7.2/tmuxinator, /c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.7.2/bin/mux)

### `0.8.0` error

    ERROR:  While executing gem ... (Errno::ENOENT)
        No such file or directory @ rb_file_s_symlink - (/c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.8.0/tmuxinator, /c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.8.0/bin/mux)

### `0.9.0` error

    /c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.9.0/bin/tmuxinator
    ERROR:  While executing gem ... (Errno::ENOENT)
        No such file or directory @ rb_file_s_symlink - (/c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.9.0/completion/tmuxinator.fish, /c/Users/foo/.gem/ruby/2.3.0/gems/tmuxinator-0.9.0/completion/mux.fish)

### Setup

    $ ruby -v
    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-msys]

    $ gem -v
     2.5.1

    $ uname -a
     MINGW64_NT-6.1 FOOMACHINE 2.6.0(0.304/5/3) 2016-09-07 20:45 x86_64 Msys

**Comment by safecancel** [comment]
Also getting this  :'(

```
$ uname -a 
MINGW64_NT-6.1 W7E-74068 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys

$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-msys]

$ gem -v
2.6.8
```

**Comment by rsrini7** [comment]
Still same. 
But, Managed to copy files manually to respective folders and some tweaks to pass the checking on tmux availability.

❯ tmuxinator new test
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes

❯ tmuxinator start test
no server running on /tmp/tmux-197609/default
The system cannot find the path specified.
'#!D:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ethagnawl** [comment]
I'm going to close this as stale. Feel free to reopen if there's still anything to discuss.
