### ISSUE TITLE
[Question/Help needed] setting up tmuxinator with a complex "design"

### ISSUE THREAD

**Issue by chaos234** [tmuxinator/tmuxinator#512]
Hey,

I have looked arround and found finally tmuxinator to easylie setup my tmux but I am a bit confused and know I think that I can't get waht I want/need.

What I want/What I need is the following:

Having setuped two klickable bars when in the tmux session (if this is a feature from tmuxinator, then sry for this mistake).

The bottem line should have one window for each of the following: 

root, minecraft server/factorio server/ts3 music bot

The line above should then contain the windows for this user/system as followed:

root: splited window where I have on teh left side a root shell and on the right side htop and nmon

minecraft/factorio server/ts3 music bot: Here comes the first problem. My Server has restarttimes and it also runs in screen sessions which I can only acces if I am logged in with the correct user (not over "su" cmd, it must be a direct login like a fresh opned putty shell).

Also, as long as tmux(inator) is not killed the windows should automaticly trying to reattach to the terminated screen when the software behind it restarts (I hope that this is possible).

Means at first that the window is splitted like the root window but on the left side there should be the attached screens and on the right side shoult be htop on the top right and the prefered user shell on the bottom right.

I hope that this is possible because I have seen this but I don't know if this only works if I use the PubkeyAuthentication or if this also works with user+pw (if not then I must change this to get this work).

Finally I should then be ablte to can click on each tab/window for easy switch to use then the correct tmux cmd to switch through the panes.

If this isn't possible then forgett about those panes and use for each one window.
Well, since the secound part will be multiplied only one pice of the required code is needed.

I hope you can help me because even with up to 4 monitors it is horrible to have over 5 putty terminals open.

**Comment by chaos234** [comment]
Push

**Comment by chaos234** [comment]
Push

**Comment by NicolasWebDev** [comment]
@chaos234, it is not really necessary to push issues on github, it won't get answered faster.
Moreover, would you mind putting a more explicit title for the issue?

**Comment by chaos234** [comment]
@NicolasWebDev Maybe this should be a better titel?

**Comment by adamstrickland** [comment]
@chaos234 I'm not sure what you're going for here, but it doesn't sound to me like this is an issue (i.e. a problem with `tmuxinator`), but one of understanding how to get it to (maybe) do what you'd like.  For something like that, I'd suggest the [`tmuxinator` gitter room](gitter.im/tmuxinator/tmuxinator) in order to ask questions and get feedback; what's here is not very understandable.

I'm going to close this as an issue until (if/when) we figure out there is an actual problem.

**Comment by chaos234** [comment]
@adamstrickland - Ähm ... if this will be an issue why I should then state it with Question/Help needed? This would make no sence and sorry but my text is fully understandable since I have written it detailed.

Closing this since it isn't resolved, is not the right way. Especialy then when you have no understanding what I want (then leave it to other ones).
