### ISSUE TITLE
Missing ~/.bin/tmuxinator.bash

### ISSUE THREAD

**Issue by mzaharie** [tmuxinator/tmuxinator#513]
`$ source ~/.bin/tmuxinator.bash`
> -bash: /home/mzaharie/.bin/tmuxinator.bash: No such file or directory

Had to use the one from gem source folder:
`source ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tmuxinator-0.9.0/completion/tmuxinator.bash`

Using: 
> rbenv 1.1.0-2-g4f8925a
> ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
> tmuxinator (0.9.0)

**Comment by vchernomor** [comment]
@mzaharie  you should first download it, as Readme tells 

> Download the appropriate completion file from the repo and source the file
