### ISSUE TITLE
Fish dir?

### ISSUE THREAD

**Issue by nathantech2005** [tmuxinator/tmuxinator#516]
How do we get involved to fix your docs? They aren't followable. The README needs to tell me how I create a dir named fish.

**Comment by J3RN** [comment]
## Documentation

To contribute to our documentation, navigate to https://github.com/tmuxinator/tmuxinator/edit/master/README.md.

Another way to get to that page is to click README.md from the file list on https://github.com/tmuxinator/tmuxinator, then click the pencil icon on the top-right of that page.

## Completions

I actually got the [Tmuxinator completions added to fish some years ago](https://github.com/fish-shell/fish-shell/blob/master/share/completions/tmuxinator.fish). The only reason to download and use the completions from this repository are to alias `mux` to `tmuxinator`, which is a matter of personal preference.

Your [fish configuration should be living in `~/.config/fish/config.fish`](https://fishshell.com/docs/current/tutorial.html#tut_startup), which I believe is created when fish is first started. Fish will look for completion files in `~/.config/fish/completions/` first, so the documentations suggests that you create that directory (unless it already exists) and download the [completions from our repository](https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish) into there.

I hope that helps!
