### ISSUE TITLE
High Sierra: tmuxinator start <project> works, mux <project> does not

### ISSUE THREAD

**Issue by dep** [tmuxinator/tmuxinator#562]
I updated to High Sierra last night, and since then I've been getting the following error when trying to execute `mux <project>` -- It's worth noting that `tmuxinator start <project>` works just fine.  Here is the error output:

zsh: /usr/local/bin/mux: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin: no such file or directory

For what it's worth, I've reinstalled tmuxinator, rvm/Ruby as well as followed the 'Completion' instructions in your `README`

**Comment by jrobichaud** [comment]
I had the same problem. 

I only ran `gem install tmuxinator` and it started working.

**Comment by dep** [comment]
Sadly reinstalling the gem didn't work for me.

**Comment by jrobichaud** [comment]
I am using `gem` version `2.6.13` if it can help troubleshooting.

**Comment by dep** [comment]
I am also using `2.6.13` - thank you for replying.

**Comment by niemalsnever** [comment]
This might warrant another issue, but in the meantime, may I ask which version of Ruby you run? Using tmuxinator under High Sierra freezes terminal completely oftentimes for me. I'm running Ruby 2.4.x (whichever version comes bundled with macOS 10.13). I will update this comment once my laptop is working again to provide more version information.

**Comment by jrobichaud** [comment]
I use `brew`'s ruby

```bash
ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
```

**Comment by Toddses** [comment]
I'm with jrobichaud. I use homebrew's ruby, and simply ran `gem install tmuxinator` and everything started working again.

**Comment by hieast** [comment]
>head `which tmuxinator`
>#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
>\#
>\# This file was generated by RubyGems.
>\#
>\# The application 'tmuxinator' is installed as part of a gem, and
>\# this file is here to facilitate running it.
>\#

require 'rubygems'```
changing the interpreter path to  `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby` should work for you
