### ISSUE TITLE
invalid option: default-path

### ISSUE THREAD

**Issue by JamesYuan** [tmuxinator/tmuxinator#566]
Hi,
Only one windows is shown, and reproduce it like this.

`
$ # just new a demo, save and quit

$ tmuxinator new demo

$ # start it, only 1 window is shown, "kill-server" in the tmux

$ tmuxinator demo
invalid option: default-path
can't find pane 2
can't find window 2
can't find window 3
[server exited]
`
`
$ tmuxinator -v
tmuxinator 0.10.0

$ brew info tmux
tmux: stable 2.6 (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/HEAD-45ee118 (10 files, 689.4KB) *
  Built from source on 2017-08-02 at 11:43:21
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
==> Dependencies
Build: pkg-config ✔
Required: libevent ✔
Optional: utf8proc ✔
==> Options
--with-utf8proc
	Build with utf8proc support
--HEAD
	Install HEAD version
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
`

Thanks,
James.

**Comment by JamesYuan** [comment]
I just uninstall and install the tmux again, it works well now.

**Comment by coddingtonbear** [comment]
I *think* what your re-installation might've done is instead downgraded you to a version of tmux before this change: https://github.com/tmux/tmux/blob/37f83adca8b965133ebdaeebea790ae897bd7175/CHANGES#L517
