### ISSUE TITLE
Option to quiet tmux version warning

### ISSUE THREAD

**Issue by adamstrickland** [tmuxinator/tmuxinator#583]
As suggested in https://github.com/tmuxinator/tmuxinator/pull/574#issuecomment-349469851, add a `--quiet` flag/option to send tmux version warning(s) to /dev/null

**Comment by p-becker** [comment]
Can be closed.

I apparently didn't use [one of the magic keywords](https://help.github.com/articles/closing-issues-using-keywords/) in the pull request 🙈
