### ISSUE TITLE
Add your zsh theme and tmux theme to the FAQ section

### ISSUE THREAD

**Issue by chris-fa** [tmuxinator/tmuxinator#584]
It looks clean and awesome, please consider it adding to the FAQ section.

[image here](https://camo.githubusercontent.com/9b914113e5e2377e9d7fa93112c0639f398bb8ba/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3134313231332f3931363038342f30363566656637632d666538322d313165322d396332332d6139363232633764383363332e706e67)

**Comment by chris-fa** [comment]
bump

**Comment by ethagnawl** [comment]
I'm not convinced this information belongs in the README.

Maybe @Soliah feels otherwise? If not, maybe they could share that information here.

**Comment by Soliah** [comment]
The theme is based off of https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup

I don't actually use that theme anymore, I use https://github.com/sindresorhus/pure now (also part of prezto) as it was a bit of a pain keeping the theme in sync with upstream.

For those interested my dotfiles are here: https://github.com/Soliah/dotfiles
