### ISSUE TITLE
How to run command after switching to powershell?

### ISSUE THREAD

**Issue by dereklin** [tmuxinator/tmuxinator#592]
Does tmuxinator support powershell?

I am running tmux on cygwin.

I have a pane config that looks like this:
```
          - winpty powershell
          - npm run storybook
          - tmux send-keys Enter
```
It switches to powershell.  Then I want to run a npm script and hit Enter to run it.

When this is executed, I see this next to the prompt:
```
> npm run storybooktmux send-keys Enter
```
What is the proper way to send a carriage return in this case?

**Comment by ethagnawl** [comment]
> What is the proper way to send a carriage return in this case?

An example would be:

`tmux send-keys -t "session-name":0.0 echo\ hi Enter`

In this example: 
- "session-name" is the name of the tmux session
- 0 is the window index
- 0 is the pane index

See the `send-keys` entry in `man tmux`.
