### ISSUE TITLE
~/.bin/tmuxinator.zsh file is missing

### ISSUE THREAD

**Issue by feimosi** [tmuxinator/tmuxinator#596]
I'd like to use the provided completion script, but it's not available in the path mentioned in the docs. I found it in the following path:
`/usr/lib/ruby/gems/2.5.0/gems/tmuxinator-0.10.1/completion/tmuxinator.zsh`
although that's a really bad idea to use it inside `.zshrc` (any version change would break it).

What would you recommend?

**Comment by ecly** [comment]
@feimosi from the readme:

> Download the appropriate completion file from the repo and source the file. The following are example where the completion file has been downloaded into ~/.bin.

**Comment by feimosi** [comment]
Sorry, I somehow missed that.
So basically after every tmuxinator update I need to download the completion file manually, right?

**Comment by ecly** [comment]
@feimosi 
The file hasn't been updated for 2 years and is unlikely to be changed. You basically download it and store it entirely independently from your tmuxinator installation and just source it from whatever location you've decided to store it at, in your .zshrc.
So after doing that just once you shouldn't have any maintenance, even when you update tmuxinator.

**Comment by feimosi** [comment]
Sure, makes sense, thanks :+1:
