### ISSUE TITLE
new project configs in non-default directory. 

### ISSUE THREAD

**Issue by tristansokol** [tmuxinator/tmuxinator#621]
Hi, I have been having some trouble with my [project configuration location](https://github.com/tmuxinator/tmuxinator#project-configuration-location). I do not have any of the variables set:
```bash
$ echo $XDG_CONFIG_HOME $TMUXINATOR_CONFIG

$
```
but my projects are being created in ~/.config/tmuxinator

I tried explicitly setting `$TMUXINATOR_CONFIG` to ~/.tmuxinator and that did create new projects in  ~/.tmuxinator but the would not have the project template, and then would always run the project as if it was saved with the default template, even if I pasted in a custom one.

I am on a mac, 10.13.4
```
$ tmuxinator version
tmuxinator 0.11.1
```

**Comment by ethagnawl** [comment]
Hi, @tristansokol. Thanks for reporting these issues. 

I can confirm that the first one (use of ~/.config/tmuxinator) is a bug. It seems like the XDG variable check in Tmuxinator::Config::xdg _always_ returns `"/home/me/.config/tmuxinator"`.

I'll need to dig into the second (use of default template) when I find a few free minutes. (Depending on whether or not they're related, I may create a new ticket for the second issue.)

**Comment by ethagnawl** [comment]
Also, in the meantime, you should be able to place the project files wherever you'd like and pass the path to `tmuxinator start` using the `-p` flag. (e.g. `tmuxinator start -p ~/.tmuxinator/foo.yml`)

**Comment by ethagnawl** [comment]
So, I think the config directory issue has two possible solutions:

- change the documentation to reflect the current implementation (e.g. new projects will be created in the XDG default (~/.config/tmuxinator) directory whether or not XDG has been installed or related env vars have been set) and leave the implementation as is
- change the implementation to match the documentation and continue to use ~/.tmuxinator for new projects unless one of `$XDG_CONFIG_HOME` or `$TMUXINATOR_CONFIG` variables have explicitly been set
