### ISSUE TITLE
latest stable release version? 0.11.2 or 0.11.3?

### ISSUE THREAD

**Issue by ilovezfs** [tmuxinator/tmuxinator#632]
https://github.com/tmuxinator/tmuxinator/releases/latest says 0.11.2 but https://github.com/tmuxinator/tmuxinator/releases shows there is a 0.11.3

**Comment by ethagnawl** [comment]
@ilovezfs Thanks for reporting this. Fixed.

**Comment by ilovezfs** [comment]
@ethagnawl you're welcome! Voilà https://github.com/Homebrew/homebrew-core/pull/28931
