### ISSUE TITLE
send <password> through tmuxinator? 

### ISSUE THREAD

**Issue by saamkhya** [tmuxinator/tmuxinator#636]
I am trying to login to the app. 
The app first requires to be launched on the shell using the name, say "myApp" 
after that it asks for username: <usernameA> and then password <passwordA>
 I am doing this in the tmuxinator app.yml
windows:
    - myApplication:
           - myApp
           - <usernameA>
          -  <password A> 

It is successfully running the application, and then taking the username, however, it fails to accept the password.

**Comment by raiyuza** [comment]
I propose closing this issue in 7 days from now.


Might Add a segment in the readme under tips and trick, however this is more Linux know how then its a tmuxinator issue!

**Comment by raiyuza** [comment]
We should close this issue.
