### ISSUE TITLE
add new window but I couldn't find it

### ISSUE THREAD

**Issue by huerbt** [tmuxinator/tmuxinator#648]
I added new windows to existing project, but I couldn't find new windows when I entered the project again.
I have a existing project，it has 4 windows. I modified the configuration and added a window.  I couldn't find it when I entered the project again.Why?

**Comment by huerbt** [comment]
Hi,@ethagnawl My steps are as follows.
1. I created test project
name: test
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f log/development.log
  - new4:
  - new5:
  - new6:
  - new7:
  - new8:
  - new9:
  - new10:    
2.I saved it and then I typed  mux text, entered test porject, everything was ok.
3.I used CTRL+b d 
4.I typed mux o text,and modified the configuration file（add new window --‘new11’）
name: test
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f log/development.log
  - new4:
  - new5:
  - new6:
  - new7:
  - new8:
  - new9:
  - new10:   
  - new11:
5. I  I typed  mux text again, then I couldn't find 'new11' window（Just have 'editor,server,log,new4...new10 windows)

tmux version is 2.7
tmuxinator version is 0.12.0

**Comment by ethagnawl** [comment]
Thanks for clarifying, @huerbt. Unfortunately, tmuxinator doesn't currently reload your project config file when you reattach to an existing session -- you'll have to run `tmuxinator stop ...` or kill the session via tmux. I'm going to close this for now, but if you feel this is worth exploring, feel free to update/reopen this issue or create a new one.
