### ISSUE TITLE
Compatibility with tmux 2.8

### ISSUE THREAD

**Issue by Ikke** [tmuxinator/tmuxinator#653]
[Tmux 2.8][0] is out, and this results in a deprecation warning for tmuxinator:

> DEPRECATION: You are running tmuxinator with an unsupported version of tmux.
> Please consider using a supported version:
> (1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7)

Though tmuxinator does still seem to work.

[0]:https://github.com/tmux/tmux/releases/tag/2.8

**Comment by fluxsauce** [comment]
In the interim, to downgrade `tmux` if you installed and upgraded using `brew` on a Mac:

```
brew switch tmux 2.7
```

**Comment by ethagnawl** [comment]
[tmuxinator v0.13.0 has been published to rubygems.org.](https://rubygems.org/gems/tmuxinator/versions/0.13.0)
