### ISSUE TITLE
What are the layout options?

### ISSUE THREAD

**Issue by mikl** [tmuxinator/tmuxinator#66]
In the example code you have `layout: main-vertical` for the editor tab, but I can't find any mention of what other options are available for the layout setting. Is it documented anywhere?

**Comment by gideongoat** [comment]
This layout creates 3 unequally sized panes with vim in one of them.  Be careful with spaces and if you try this make sure to include the colon and a newline on the last two line exactly as shown: 
#***********start example***********
windows:
  - editor:
      layout: main-vertical
      panes:
        - tmux split-window -d ; M=0; while [ "$M" -lt 9 ]; do (( M+=1 )); tmux resize-pane -D; done; vim
        - ;

**Comment by rhdxmr** [comment]
5 default layouts are: even-horizontal, even-vertical, main-horizontal, main-vertical, and tiled.
Key bindings of each layout:
even-horizontal ⇒ M-1
even-vertical ⇒ M-2
main-horizontal ⇒ M-3
main-vertical ⇒ M-4
titled ⇒ M-5

**Comment by Vafa-Andalibi** [comment]
Dead link: [the five standard layouts](http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html#contenttoc6)

**Comment by Abdull** [comment]
> Dead link: [the five standard layouts](http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html#contenttoc6)

Alive links:
* tmux manpage at OpenBSD
  * https://man.openbsd.org/OpenBSD-current/man1/tmux.1#even-horizontal
  * https://man.openbsd.org/OpenBSD-current/man1/tmux.1#even-vertical
  * https://man.openbsd.org/OpenBSD-current/man1/tmux.1#main-horizontal
  * https://man.openbsd.org/OpenBSD-current/man1/tmux.1#main-vertical
  * https://man.openbsd.org/OpenBSD-current/man1/tmux.1#tiled
* tmux wiki at GitHub
  * https://github.com/tmux/tmux/wiki/Getting-Started#window-layouts
