### ISSUE TITLE
Allow .yaml and .yml file extensions for tmuxinator projects

### ISSUE THREAD

**Issue by rodrigopandini** [tmuxinator/tmuxinator#663]
**Describe the bug**
`.yaml` file extensions don't work for tmuxinator projects 

**To Reproduce**
- create a `sample.yml` in `~/.tmuxinator` folder
- create a `sample.yaml` in `~/.tmuxinator` folder

**Expected behavior**
- `sample.yml` works!
- `sample.yaml` NOT works.

**Environment**
 - tmuxinator Version: "tmuxinator 0.13.0"
- tmux Version: "tmux 2.6"
 - Ruby Version: "ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]"
 - OS: "Ubuntu 18.04.1 LTS"

**Additional information**
yaml and yml are common extesions used to denote a YAML file.
Seems like tmuxinator not recognize yaml as a valid extension for a YAML file.
Sounds reasonable accept both type of extension.

**Comment by ethagnawl** [comment]
Hey, @rodrigopandini. Thanks for reporting this. 

[The FAQ on yaml.org](https://yaml.org/faq.html) says, "Please use ".yaml" when possible", so this seems like a reasonable request to me.

**Comment by ethagnawl** [comment]
Closed via #664.
