### ISSUE TITLE
Bundler fails after upgrading ruby version 

### ISSUE THREAD

**Issue by michal-samluk** [tmuxinator/tmuxinator#685]
**Describe the bug**
I have ruby-2.6.1  installed via RVM and when I run my project in terminal with command: `bundle exec rails s -p 3001` it starts successfully. 
My tmuxinator config runs such command in one of the panes. It fails with error: `You must use Bundler 2 or greater with this lockfile`. 
I am getting same message while running: `gem`, `bundle` in this pane. 

After running `printenv` I see: `BUNDLER_ORIG_GEM_HOME` and `BUNDLER_ORIG_GEM_PATH` variable pointing to older version of my ruby (2.5.3). I do not see such env variable while being in terminal without tmux. 

Command `rvm use` fails with same error (+ gives stacktrace for lockparser)

**To Reproduce**
Upgrade ruby from 2.5.x to 2.6.1 altogether with bundler (new version 2.0.1) 

**Expected behavior**
It should work :) 

**Environment**
 - tmuxinator Version: tmuxinator 0.15.0
 - tmux Version: tmux 2.8
 - Ruby Version: 2.6.1 (and previously 2.5.3) 
 - OS: osx

**Comment by ethagnawl** [comment]
Hi, @michal-samluk.

Are you still seeing this issue? Unfortunately, I'm unable to reproduce it on my machine (Debian 9.8).

**Comment by michal-samluk** [comment]
Hi @ethagnawl  No, I do not see the issue disappeared. So it works now. 
It started working after upgrading to ruby-2.6.2.
