### ISSUE TITLE
environments option

### ISSUE THREAD

**Issue by griffinqiu** [tmuxinator/tmuxinator#687]
**Is your feature request related to a problem? Please describe.**

I want to use the different docker host for different projects. The projects boot by tmuxinator. So that, I have to run the export environments command in every windows and every panels. I know the command of pre_window, but it does not work for new window or panel after tmux ran.

**Describe the solution you'd like**

It is better to add an option like environments. It effective for every window and panel, even the new window.

**Comment by ethagnawl** [comment]
Hi, @griffinqiu. 

I think one solution here might be to introduce a hook class for window events (similar to the existing [Tmuxinator::Hooks::Project class](https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/hooks/project.rb)).

In the meantime, you could use tmux hooks from within your tmux config file* to achieve this behavior. If need be, you could create a config file for this project and have your tmuxinator project use it via the `tmux_options` option (e.g. `tmux_options: -f ~/.tmux.conf-with-exports`).

* `set-hook before-new-window 'run "export FOO=bar"'`
* `set-hook before-split-window 'run "export FOO=bar"'`

**Comment by ethagnawl** [comment]
I'm going to close this as stale. Please feel free to reopen if there's anything more to discuss.
