### ISSUE TITLE
Alternative terminology for layouts

### ISSUE THREAD

**Issue by anhari** [tmuxinator/tmuxinator#688]
I can never remember what layout I want with the current naming using `vertical` and `horizontal`. For example, `even-horizontal` creates three _vertically_ oriented panes that span horizontally across the terminal.

**Describe the solution you'd like**
Backward-compatible new layout naming using the terms `rows` and `columns`.

i.e. 

`even-horizontal` -> `even-columns`
`even-vertical` -> `even-rows`

**Describe alternatives you've considered**
Perhaps a command that prints the layouts in ASCII.

**Comment by ethagnawl** [comment]
Hey, @anhari. 

This sounds reasonable to me. Would you consider submitting a PR?

As you may already know, the existing names are courtesy of tmux. So, you could also try opening an issue/PR upstream, as that'd be the ideal solution.

**Comment by ethagnawl** [comment]
Lets continue to lean on the names provided by tmux.
