### ISSUE TITLE
Cannot load XDG requirement after fresh install

### ISSUE THREAD

**Issue by stackptr** [tmuxinator/tmuxinator#708]
**Describe the bug**
After updating Ruby from the older macOS stock version (which tmuxinator does not support) to 2.4.6 via `rbenv` (also, previously, via `rvm` with the same result), I get the following traceback:

```
/Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `require_relative': cannot load such file -- /Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg/index (LoadError)
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `<module:XDG>'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:26:in `<top (required)>'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/tmuxinator-1.1.0/lib/tmuxinator.rb:6:in `<top (required)>'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/corey/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/tmuxinator-1.1.0/bin/tmuxinator:5:in `<top (required)>'
	from /Users/corey/.rbenv/versions/2.4.6/bin/tmuxinator:23:in `load'
	from /Users/corey/.rbenv/versions/2.4.6/bin/tmuxinator:23:in `<main>'
```

**To Reproduce**
On a fresh machine, I first tried `gem install tmuxinator` and was greeted with an error stating I needed an updated `ruby`. First I tried using `rvm`, install the latest version available through that, and received the same traceback above. Since the original `gem install` on the older version of ruby installed `xdg`, I used `gem uninstall xdg` (and `gem uninstall tmuxinator`) to avoid leaving different versions of things around.

Since this didn't work, I saw that the documentation around supporting interpreter managers via `pre_window` mentions `rbenv` so I used `rvm implode` (did some further cleanup myself) and then pulled in that instead. I followed the process specified [here](https://medium.com/@namangupta01/replacing-rvm-with-rbenv-in-os-x-9dea622bd639). I am not experienced in the Ruby ecosystem, but nothing jumped out as failing.

After `rbenv install 2.4.6` (getting just the minimum version required this time) and setting it with `rbenv global 2.4.6` I get the same error, after installing:

```zsh
❯ ruby -v
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin18]

❯ gem install tmuxinator
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: thor-0.20.3.gem (100%)
Successfully installed thor-0.20.3
Fetching: xdg-2.2.4.gem (100%)
‼️ Development of this project has been transfered here: https://github.com/bkuhlmann/xdg. This will be the last version supported within the 2.2.x series. Be aware major breaking changes will be introduced in the upcoming 3.0.0 release (2019-06-01).
Successfully installed xdg-2.2.4
Fetching: tmuxinator-1.1.0.gem (100%)

    __________________________________________________________
    ..........................................................

    Thank you for installing tmuxinator.

    Make sure that you've set these variables in your ENV:

      $EDITOR, $SHELL

    You can run `tmuxinator doctor` to make sure everything is set.
    Happy tmuxing with tmuxinator!

    ..........................................................
    __________________________________________________________
  
Successfully installed tmuxinator-1.1.0
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Parsing documentation for xdg-2.2.4
Installing ri documentation for xdg-2.2.4
Parsing documentation for tmuxinator-1.1.0
Installing ri documentation for tmuxinator-1.1.0
Done installing documentation for erubis, thor, xdg, tmuxinator after 1 seconds
4 gems installed
```

My `$EDITOR` and `$SHELL` are set and `tmuxinator doctor` fails in the same manner as the other commands.

**Expected behavior**
Should be able to start a new tmuxinator session

**Environment**
 - tmuxinator Version: `tmuxinator -v` fails with aforementioned error
- tmux Version: tmux 2.9a
 - Ruby Version: ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin18]
 - OS: macOS Mojave 10.14.5

**Comment by juhlila** [comment]
i had the same problem and fixed it by setting xdg version to 2.2.3

**Comment by joshuamcginnis** [comment]
I'm receiving the same error on a fresh install.

**Comment by GrumpyRainbow** [comment]
Looks like a new version of xdg was released to address this.  https://github.com/bkuhlmann/xdg/blob/master/CHANGES.md

**Comment by ethagnawl** [comment]
Thanks, all. I have a fix pending and will hope to get a release out later today.

**Comment by ethagnawl** [comment]
A new version of tmuxinator (1.1.1) has been released which contains the fix for this issue.

**Comment by stackptr** [comment]
Great, confirming that this appears fixed
