### ISSUE TITLE
macOS Catalina Support

### ISSUE THREAD

**Issue by FlorianWendelborn** [tmuxinator/tmuxinator#712]
**Describe the bug**
On macOS Catalina, `ruby` was upgraded to `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`. This leads to `tmuxinator` crashing with `zsh: /usr/local/bin/tmuxinator: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory`.

**To Reproduce**
1. Install macOS Catalina
2. `gem install tmuxinator`
3. See `tmuxinator` light up in flames

**Expected behavior**
`tmuxinator` should not die on macOS Catalina.

**Environment**
 - tmuxinator Version:
```
Traceback (most recent call last):
	2: from /usr/local/bin/tmuxinator:22:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:262:in `bin_path'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem tmuxinator (>= 0.a) with executable tmuxinator (Gem::GemNotFoundException)
```

- tmux Version: `tmux 2.9`
 - Ruby Version: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`
 - OS:

```
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A471t)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBook Pro
      User Name: Username (username)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 14:51
```

**Additional information**
—

---

## EDIT: Investigating this Further

There might be something else wrong. After `gem remove tmuxinator`, my `tmuxinator` binary was still there. So, I investigated. Turns out `gem` installed the binary to `/usr/local/lib/ruby/gems/2.6.0/bin/tmuxinator`.

Using that version, `tmuxinator` seems to work. Any idea how/why this happens? and how this can be fixed?

**Workaround**: `ln -s /usr/local/lib/ruby/gems/2.6.0/bin/tmuxinator /usr/local/bin/tmuxinator`

**Comment by ethagnawl** [comment]
Hi,

1.) It looks like some part of your system is trying to use Ruby 2.3 which doesn't appear to exist.

> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory

2.) I'm not sure it'll address the problem you're seeing, but you may also want to upgrade to a more recent version of tmuxinator (you're using 0.13.0 and the current release is 1.1.1).

**Comment by FlorianWendelborn** [comment]
@ethagnawl

Regarding 1: Yes, I think macOS Catalina upgraded `ruby` to `2.6` and removed `2.3`.

Regarding 2: I can’t find out my `tmuxinator version`. The stack trace below the `Tmuxinator version:` is exactly what `tmuxinator -v` gave me. With the workaround I mentioned at the very bottom, my `tmuxinator` works again and I’m now on `1.1.1`.

**Comment by ethagnawl** [comment]
Since this issue seems to be an OS/environment issue (perhaps you need to add `/usr/local/lib/ruby/gems/2.6.0/bin` to `$PATH` in .bash_profile or whatever MacOS uses?), I'm going to close it for now. Feel free to reopen if you determine that tmuxinator is misbehaving in some way.

**Comment by fingerpich** [comment]
Faced with the same problem and its fixed by the following commands

```
rm $(whereis tmuxinator)
brew install tmuxinator
```
