### ISSUE TITLE
Unable to start Tmuxinator

### ISSUE THREAD

**Issue by lukeberry99** [tmuxinator/tmuxinator#714]
**Describe the bug**
I get the following error when running `tmuxinator` 

``` bash
Traceback (most recent call last):
	6: from /Users/luke/.rvm/gems/ruby-head/bin/ruby_executable_hooks:10:in `<main>'
	5: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	4: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	3: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	2: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	1: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/luke/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)
	10: from /Users/luke/.rvm/gems/ruby-head/bin/ruby_executable_hooks:10:in `<main>'
	 9: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	 8: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	 7: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	 6: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	 5: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 4: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 3: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 2: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 1: from /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fa5de00f060> (NoMethodError)
```

**To Reproduce**
`$ tmuxinator`

**Expected behavior**
Tmuxinator should run

**Environment**
- tmuxinator Version: fresh install (-v gives me the same error)
- tmux Version: tmux 2.7
- Ruby Version: ruby 2.7.0dev (2019-07-19T08:18:42Z trunk 0a7093a8e9) [x86_64-darwin18]
- Gem version: 3.1.0.pre1
- OS: MacOS Mojave v10.14

**Comment by ethagnawl** [comment]
Hi, @lukeberry99. 

I haven't been able to dig too deeply into this, but it doesn't seem to be a problem with Ruby 2.7. [I added 2.7.0-preview1 to the tmuxinator test matrix and it didn't break the CI build.](https://travis-ci.org/tmuxinator/tmuxinator/jobs/561548092)

> /Users/luke/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fa5de00f060> (NoMethodError)

Based on the above, it'd seem to be a RubyGems or Bundler issue. I don't have a Mac, so maybe someone else with a similar setup to yours could chime in? (/CC @tmuxinator/tmuxinator)

**Comment by thanateros** [comment]
Exact same issue.

* tmuxinator version: 1.1.1
* tmux version:  2.88
* Ruby version: 2.7.0dev (via RVM version 1.29.9-next)
* Gem version: 3.1.0.pre1
* OS: Ubuntu  Server 19.04

All freshly installed from scratch yesterday.

**Comment by lukeberry99** [comment]
@ethagnawl @thanateros downgrading to Ruby `2.6.3` and gem `3.0.3` got it working for me. 

I'm happy to do more investigation

**Comment by ethagnawl** [comment]
Closing as this seems not to be a tmuxinator issue. Feel free to reopen if there's more to discuss.

**Comment by thanateros** [comment]
@lukeberry99 thanks I'll try that.
