### ISSUE TITLE
Please add support for rubygem-xdg 3.0

### ISSUE THREAD

**Issue by cryptomilk** [tmuxinator/tmuxinator#716]
**Describe the bug**

Please add support for rubygem-xdg 3.0.

**Comment by ethagnawl** [comment]
Hi, @cryptomilk. Why are you requesting this change?

**Comment by cryptomilk** [comment]
Because distributions updated to rubygem-xdg 3.0.1 and tmuxinator stopped working for me.

The requirement is currently:
>= 2.2.5
< 3.0.0

So it doesn't work with current tmuxinator.

**Comment by ethagnawl** [comment]
> distributions

Could you be more specific? 

Also, how are you installing tmuxinator? RubyGems _should_ handle installing and referencing the appropriate version of XDG for you.

Unfortunately, it's not as simple as just removing the upper bound on the version constraint, as XDG >= 3.0.0's API is not compatible with tmuxinator. (Seems to primarily be the use of `XDG[...]`.) It's possible that there are backwards compatible methods, but I'd like to understand why this is even necessary before looking further into it.
