### ISSUE TITLE
Tmuxinator can't find $EDITOR, but it exists

### ISSUE THREAD

**Issue by nchase** [tmuxinator/tmuxinator#718]
**Describe the bug**
tmuxinator thinks I don't have an `EDITOR` environment variable, but I do. See below:

**To Reproduce**
```
$ echo $EDITOR
vim 

$ tmuxinator doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> No
Checking if $SHELL is set ==> Yes
```

**Expected behavior**
```
$ tmuxinator doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> No
Checking if $SHELL is set ==> Yes
```
**Environment**
 - tmuxinator Version: tmuxinator 1.1.1
- tmux Version: tmux 2.6
 - Ruby Version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
 - OS:  Ubuntu 18.04.2

**Comment by ethagnawl** [comment]
Where/how are you setting `EDITOR`?

**Comment by nchase** [comment]
Hi @ethagnawl - I’m setting it as the first line of my zshrc. At what point does tmuxinator check for $EDITOR?

**Comment by ethagnawl** [comment]
> At what point does tmuxinator check for $EDITOR?

If you're using the `doctor` subcommand, this is checked pretty early on. Roughly, you can follow the path from:
- https://github.com/tmuxinator/tmuxinator/blob/5709ff08847e71e6c3d0b82cc89f788df8b72906/bin/tmuxinator
- https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/cli.rb
- https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/doctor.rb

As far as I can remember, nothing out of the ordinary is happening here (spawning shells or anything), it's just the Ruby program running and looking up values in `ENV`. I'd be curious to know what the result of you running `irb` from your zsh shell and then looking up `ENV['EDITOR']` is.

**Comment by nchase** [comment]
>  I'd be curious to know what the result of you running irb from your zsh shell and then looking up ENV['EDITOR'] is.

Ha, that's interesting. Ruby doesn't seem to think I have an `$EDITOR`:

```ruby
irb(main):001:0> ENV['EDITOR']
=> nil
```

**Comment by ethagnawl** [comment]
I'm relieved to know it's not a tmuxinator issue. :sweat_smile: 

Could you share the relevant line from your .zshrc?

**Comment by nchase** [comment]
The corresponding area of my .zshrc is really simple, I set my editor as
the first line in it: https://github.com/nchase/dotfiles/blob/master/.zshrc

I wonder if I set this in a bashrc as well if it'll just work.

**Comment by ethagnawl** [comment]
Perhaps it's because you're not explicitly exporting the variable? 

Try: `export EDITOR=vim`

**Comment by nchase** [comment]
That was exactly it. I don't know how many years I've had this setup without having to do that, but it seems like I should. Thank you @ethagnawl!
