### ISSUE TITLE
Incorrect version detection

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [tmuxinator/tmuxinator#728]
Running tmuxinator with Tmux built from`HEAD` is problematic for non-trivial layouts.
Upon launch an error about unsupported option `default-path` is output by Tmux server.

A `HEAD` Tmux currently reports itself as `next-3.1` (`$ tmux -V`), which fails https://github.com/tmuxinator/tmuxinator/blob/6442103d03c3c95e73e86db2044cf35d7a13f55b/lib/tmuxinator/config.rb#L63-L73 logic

```ruby
>> 'next-3.1'.split(" ")[1]
=> nil
```

Hence, later on in tmuxinator where checks are made against `version < 1.8` it incorrectly assumes that I'm running ye'olde Tmux.

**Comment by ethagnawl** [comment]
Thanks for reporting this, @aleksandrs-ledovskis.

We can see about handling this and similar edge cases a little more gracefully. However, as discussed elsewhere (#574), there will be dragons when using a version of tmux which isn't explicitly supported -- as indicated by the deprecation warning. This could be better documented and if you have any feedback on how best to convey that, it'd be appreciated.

**Comment by aleksandrs-ledovskis** [comment]
@ethagnawl Documentation is good, but correct logic is better 🙃. 

I created a PR to improve version detection so that currently not supported versions (e.g. `next-3.1` which is how currently `tmux` reports itself on `master` branch) would not be incorrectly detected as `0.0`, causing invalid assumptions in feature support guards.
