### ISSUE TITLE
Configure invocation of tmux

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [tmuxinator/tmuxinator#750]
It's often the case (due to the need for SSH forwarding, etc) that one may need many different ways of invoking `tmux`.

It would be nice to be able to specify on a per-project basis (and perhaps globally as well), the command for how to invoke `tmux`.

**Comment by ethagnawl** [comment]
You should be able to achieve this using the top-level `tmux_command` option. 

It's present in the sample.yml in the README but could be better documented. Feel free to open a PR if you have any suggestions.

**Comment by ttttcrngyblflpp** [comment]
Oh totally missed that, thanks for pointing it out.
