### ISSUE TITLE
Bump xdg gem dependency to 3.0.1

### ISSUE THREAD

**Issue by Dridi** [tmuxinator/tmuxinator#753]
Following up on https://github.com/tmuxinator/tmuxinator/issues/731#issuecomment-618756858, with my Fedora hat on I would like to see up-to-date dependencies. I didn't review test dependencies because I don't have enough bandwidth to maintain more Ruby packages on Fedora, so I'll leave those to your discretion.

I understand the ruby interpreter constraint, even though that wouldn't be a problem on Fedora 32 and 33, so 3.0.1 sounds like a reasonable update.

Thanks!

**Comment by ethagnawl** [comment]
After digging a little deeper into the XDG gem's releases and gemspec, it turns out that 3.0 introduced a requirement that Ruby be >= 2.6. So, we're going to have to hold on this until Ruby 2.5 is EOL'd.

**Comment by Dridi** [comment]
So your policy is pretty much the opposite of Fedora's, which is fine. Thanks for taking the time to considering it, this will only become a problem for me if a new package requires a newer incompatible version of one of your dependencies. I'll only revisit this problem if this scenario happens, or when you bump dependencies in future releases.

I think you can close this issue, thanks.
