### ISSUE TITLE
Support tmux 3.1

### ISSUE THREAD

**Issue by keithpitty** [tmuxinator/tmuxinator#754]
**Is your feature request related to a problem? Please describe.**
tmuxinator needs to support this new version of tmux

**Describe the solution you'd like**
Update tmuxinator to support tmux 3.1.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ethagnawl** [comment]
Closed via #757 and available in [v1.1.5](https://rubygems.org/gems/tmuxinator/versions/1.1.5).
