### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by rightaway** [tmuxinator/tmuxinator#764]
Getting this error when using the latest tmux 3.1.

```
WARNING: You are running tmuxinator with an unsupported version of tmux.
    Please consider using a supported version:
    (3.0a, 3.0, 2.9a, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5)
```

Unless tmuxinator always immediately makes a release at the exact same time as tmux, this error message will regularly appear.

I think this error should only appear by default for versions that are explicitly shown to be incompatible with a particular version of tmux, where there's some breaking change that was introduced, and not just because there's a newer version.

**Comment by ethagnawl** [comment]
tmux 3.1 is supported by [the latest release](https://rubygems.org/gems/tmuxinator/versions/1.1.5) of tmuxinator.

The issue you raise has been discussed at length in the past and the position of the maintainers is that tmuxinator will maintain an explicit list of the supported versions of tmux.

You can opt out of this behavior by using the `--suppress-tmux-version-warnings` flag when starting tmuxinator.

**Comment by jaspertandy** [comment]
Just to add to this, the flag is actually `--suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING` (not "warnings"), so your command would be `tmuxinator start PROJECTNAME --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING` to fully suppress this warning.

**Comment by ivankovnatsky** [comment]
```
(3.2a, 3.2, 3.1c, 3.1b, 3.1a, 3.1, 3.0a, 3.0, 2.9a, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5)

❯ tmux -V
tmux 3.3a
```

**Comment by kimifish** [comment]
oneliner for executive wrapper named '`tmx`'. 
don't forget to type in command '`start`', won't work without it.

`echo -e '#!/bin/sh\n/usr/local/bin/tmuxinator "$@" --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING' | sudo tee /usr/local/bin/tmx && sudo chmod +x /usr/local/bin/tmx`

In my humble opinion, warnings shouldn’t interrupt the workflow. If it’s so important to remind the user about an unsupported version, it would be enough to pass the warning to "`tmux display-message`".
