### ISSUE TITLE
Describe how to create unnamed windows in documentation

### ISSUE THREAD

**Issue by johnlinp** [tmuxinator/tmuxinator#773]
**Is your feature request related to a problem? Please describe.**
I wasn't able to find the way to create unnamed windows until I saw https://github.com/tmuxinator/tmuxinator/pull/323.

**Describe the solution you'd like**
Describe how to create unnamed windows in the documentation.

**Comment by ethagnawl** [comment]
Thanks, @johnlinp. This is a great suggestion.

**Comment by johnlinp** [comment]
Thank you @ethagnawl!
