### ISSUE TITLE
Brew installation takes over Ruby's executable directory

### ISSUE THREAD

**Issue by kaka-ruto** [tmuxinator/tmuxinator#780]
**Describe the bug**
When I install Tmuxinator using Brew, it changes the Ruby executable directory, which brings up a lot of problems. For my case, I couldn't get to use the `solargraph` gem for example.

**To Reproduce**
- Uninstall your ruby installation of tmuxinator with `gem uninstall tmuxinator`
- Install Tmuxinator with `brew install tmuxinator`
- Start any tmux session with `tmux` or `tmuxinator start project-name`
- Check your Ruby's executable directory with `gem env | grep "EXECUTABLE DIRECTORY"` or just `gem env`

For my case, it was ` - EXECUTABLE DIRECTORY: /usr/local/Cellar/tmuxinator/2.0.1/libexec/bin`

**Expected behavior**
If you exit tmux (or tmuxinator) and run `gem env | grep "EXECUTABLE DIRECTORY"`, you will find the right path for your Ruby's executable directory. This should be the expected behaviour.

For my case, this was `  - EXECUTABLE DIRECTORY: /Users/kaka/.asdf/installs/ruby/2.6.5/bin`

**Environment**
 - tmuxinator Version: tmuxinator 2.0.1
- tmux Version: tmux 3.1b
 - Ruby Version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
 - OS: macOS High Sierra version 10.13.6 (17G13035)

**Comment by ethagnawl** [comment]
Hey, @kaka-ruto. The Homebrew tmuxinator formula is not maintained by the tmuxinator maintainers. You should open an issue/submit a PR to [homebrew-core](https://github.com/Homebrew/homebrew-core).

I'm going to close this for now, but feel free to reopen if you think there's more to discuss.

**Comment by kaka-ruto** [comment]
Okay, thanks @ethagnawl

**Comment by markquezada** [comment]
I also ran into this. I uninstalled from homebrew and installed via rubygems.

**Comment by kaka-ruto** [comment]
Hope it didn't take you long to figure @markquezada ! For me it took too long.

I also tried to raise this issue on homebrew-core but there pre-issue requirements were too tough/stringent to be able to.
