### ISSUE TITLE
"sh: 1: ubl: not found" on tmuxinator copy

### ISSUE THREAD

**Issue by ryanberckmans** [tmuxinator/tmuxinator#789]
**Describe the bug**
When running `tmuxinator copy foo-existing-project bar-new-project` the command fails with `sh: 1: ubl: not found`.

**To Reproduce**
Try running a `tmuxinator copy` using my environment below.

**Expected behavior**
Successful tmuxinator copy.

**Environment**
- installed tmuxinator with `sudo apt install tmuxinator` (this package is not the latest version of tmuxinator)
 - tmuxinator Version: 1.1.4
- tmux Version: 3.0a
 - Ruby Version: 2.7 (unsure of specific ruby version, it's bundled into the apt package)
 - OS: Ubuntu 20.04

**Additional information**
I couldn't find an existing issue for this `ubl` bug or a way to install the `ubl` utility (if it's a utility at all). I'm unsure if this is a tmuxinator bug or related to the method of installation (Ubuntu package).

**Comment by ethagnawl** [comment]
I'm unable to reproduce this issue on Debian, so I think you may be right in thinking that it's Ubuntu specific. I will try to reproduce on an Ubuntu machine and follow up.

**Comment by ethagnawl** [comment]
I'm unable to reproduce on Ubuntu 18.04 using tmuxinator installed via Rubygems and Aptitude. I'll try again on a more modern version when I can find some time.

**Comment by ethagnawl** [comment]
I'm also unable to reproduce on Ubuntu 20.04 using the stated versions of tmux and tmuxinator.

**Comment by ryanberckmans** [comment]
Thanks for trying. I'm good to close this.
