### ISSUE TITLE
install with apt-get

### ISSUE THREAD

**Issue by strowk** [tmuxinator/tmuxinator#797]
**Is your feature request related to a problem? Please describe.**
Cannot install it without being published in convenient package manager.

**Describe the solution you'd like**
I think this should be in apt

**Describe alternatives you've considered**
Install ruby and then install tmuxinator. I also tried installing from apt-get, but it was some sort of old version - 1.1.4-3

**Comment by ethagnawl** [comment]
This is an issue to take up with the Debian package maintainers.
