### ISSUE TITLE
Pass .yml file to `mux start`

### ISSUE THREAD

**Issue by Jasha10** [tmuxinator/tmuxinator#807]
## Feature Request

I'd love to be able to specify which .yml file to use when calling `tmuxinator start`. Maybe something like:
```sh
tmuxinator start -f ./path/to/my/config.yml
```

The use case is as follows:
I have several .yml files associated with different projects. Some projects have multiple tmuxinator .yml configuration files.
These .yml files are checked into version control; I do not want to keep them in a central location like ~/.config.

**Comment by ethagnawl** [comment]
See the -p flag in the README's "Starting a session" section.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Jasha10** [comment]
Awesome. Thanks very much for the quick reply!
