### ISSUE TITLE
Describe project configuration files using a JSON Schema for better editor experience

### ISSUE THREAD

**Issue by silesky** [tmuxinator/tmuxinator#811]
Problem: I'd like to be able to have validation and autocomplete for tmux project configuration  files.

Something like this:
![image](https://user-images.githubusercontent.com/5115498/112038696-2ec06e00-8b11-11eb-87f7-54093bd24458.png)

Some popular editors (Jetbrains / VSCode / Visual Studio) have support for json schemas that enable this kind of functionality. In VSCode, it's as easy as:
```json
  "yaml.schemas": {
    "https://json.schemastore.org/tmuxinator": [
      "tmuxinator/*.yml",
      "tmuxinator.yml"
    ]
  }
```

Would this be something we could add?

Respectfully,
Seth

**Comment by jamesbvaughan** [comment]
It would be great to add the schema to SchemaStore as well for even more automatic integration with editors that support it!

They have some docs on contributing schemas here: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md

I'm interested in taking this issue, but I'm not sure when I'll have time for it.

**Comment by hyperupcall** [comment]
Hai! ^w^

I thought it would be nice to have this feature too, so I made a [PR](https://github.com/SchemaStore/schemastore/pull/2424) for it over at SchemaStore. It will match [these files](https://github.com/SchemaStore/schemastore/blob/9680e84b93a5fe14efea21c7c11b91ee14ae76f8/src/api/json/catalog.json#L3213) by default. I suppose when that gets merged, we can close this

**Comment by silesky** [comment]
Thank you @hyperupcall. Now the following works in vscode settings:

```json
  "yaml.schemas": {
    "https://json.schemastore.org/tmuxinator": [
      ".config/tmuxinator/*.yml",
      "tmuxinator.yml"
    ]
  },
```
