### ISSUE TITLE
Support tmux 3.2

### ISSUE THREAD

**Issue by ineu** [tmuxinator/tmuxinator#812]
**Is your feature request related to a problem? Please describe.**
tmux 3.2 was releases on 13.04.2021: https://github.com/tmux/tmux/releases and is already present in ArchLinux repos. Tmuxinator seems to work with this version, however it emits the warning:
>     WARNING: You are running tmuxinator with an unsupported version of tmux.
>    Please consider using a supported version:
    (3.1c, 3.1b, 3.1a, 3.1, 3.0a, 3.0, 2.9a, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5)
> Press ENTER to continue.

**Describe the solution you'd like**
Tmux 3.2 should be added to the list of supported versions

**Comment by alk-mandrianarijaona** [comment]
There is already a PR for this #779

**Comment by ineu** [comment]
And that one is closed now, great news!

**Comment by StanczakDominik** [comment]
A tmuxinator release, even a bugfix one, to account for that, would still be helpful!
