### ISSUE TITLE
tmuxinator start [project] hangs as of 2.0.3 from homebrew

### ISSUE THREAD

**Issue by jby** [tmuxinator/tmuxinator#816]
**Describe the bug**
`tmuxinator start [PROJECT]` 
hangs indefinitely on my macOS 11.2.3 (intel) using 2.0.3 from Homebrew

**To Reproduce**
Try to start project with `tmuxinator start [PROJECT]`

**Expected behavior**
Project start with defined windows and panes

**Environment**
brew info tmuxinator
tmuxinator: stable 2.0.3 (bottled), HEAD
Manage complex tmux sessions easily
https://github.com/tmuxinator/tmuxinator
Conflicts with:
  tmuxinator-completion (because the tmuxinator formula includes completion)
/usr/local/Cellar/tmuxinator/2.0.3 (652 files, 2MB) *
  Poured from bottle on 2021-04-15 at 08:45:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tmuxinator.rb
License: MIT
==> Dependencies
Required: ruby ✔, tmux ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
fish completions have been installed to:
  /usr/local/share/fish/vendor_completions.d
==> Analytics
install: 924 (30 days), 2,558 (90 days), 11,740 (365 days)
install-on-request: 924 (30 days), 2,555 (90 days), 11,730 (365 days)
build-error: 0 (30 days)
**Additional information**

**Comment by jby** [comment]
When stopped with Ctrl-C this is printed on stdout:

```
^C/usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:352:in ``': Interrupt
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:352:in `extract_tmux_config'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:346:in `tmux_config'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:321:in `get_base_index'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:211:in `base_index'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/window.rb:107:in `tmux_window_command_prefix'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/window.rb:14:in `initialize'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:113:in `new'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:113:in `block in windows'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:112:in `map'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:112:in `with_index'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:112:in `windows'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:231:in `windows?'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/project.rb:73:in `validate!'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/config.rb:178:in `validate'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/cli.rb:196:in `create_project'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/cli.rb:263:in `start'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/lib/tmuxinator/cli.rb:430:in `bootstrap'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/gems/tmuxinator-2.0.3/bin/tmuxinator:7:in `<top (required)>'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/bin/tmuxinator:23:in `load'
	from /usr/local/Cellar/tmuxinator/2.0.3/libexec/bin/tmuxinator:23:in `<main>'
```

**Comment by rbpatt2019** [comment]
I'm getting the same error with tmuxinator installed with gem. It occurred while I was on tmuxinator v2.0.2 after I updated to tmux v3.2, but the issue persists with tmuxinator v2.0.3 as well. Tmux installed via macports, but I didn't catch this till after I reclaimed and removed the old tmux version. Currently working to downgrade, and will report back when possible.

**Comment by jby** [comment]
Ok, try killing off all running sessions and try to start from scratch. That solved my problem, which I'd say was related to an update of tmux via homebrew. Running sessions kept running, but I was unable to start new sessions.

**Comment by rbpatt2019** [comment]
Can confirm. The classic "have you tried turning it off and back on again?". I suspect related to the fact that I updated Tmux while my tmuxinator sessions were running. Cheers!
