### ISSUE TITLE
Unable to start new session after upgrading tmux

### ISSUE THREAD

**Issue by andreicorpo** [tmuxinator/tmuxinator#829]
**Describe the bug**
Can't start new session

**To Reproduce**
Whenever I try to start a project: `tmuxinator start project`,  I get errors like `can't find session: project`.

Real-world example:
```
❯ tmuxinator start dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
can't find session: dot
```

**Expected behavior**
Project starts successfully 

**Environment**
 - tmuxinator Version: `tmuxinator 3.0.0`
- tmux Version: `tmux 3.2a`
 - Ruby Version: `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`
 - OS: `MacOS BigSur 11.4`

**Comment by jeromefaria** [comment]
Experiencing the same after upgrading to 3.0.0.

- tmux 3.2a
- tmuxinator 3.0.0
- macOS 11.4 20F71

**Comment by ethagnawl** [comment]
Could you include your project config, its location (e.g. ~/.config/tmuxinator/dot.yml) and the output of `tmuxinator start dot`?

FWIW, I'm not able to reproduce this issue on Debian 10.9 with Ruby 2.6.7 and tmux 3.2a.

**Comment by nertzy** [comment]
We were able to fix this issue by restarting the tmux server. Perhaps you upgraded tmux while the previous version was still running?

```
tmux kill-server
```

**Comment by ethagnawl** [comment]
Great point, @nertzy. We should add a note to the README about this and/or pin this issue to the top of the issues page, as there are often issues like this one reported after tmux releases.

**Comment by jeromefaria** [comment]
I can confirm it works as intended after killing the tmux server. Thanks!

**Comment by ethagnawl** [comment]
@andreicorpo Can you confirm that restarting the tmux server solves your problem?

**Comment by andreicorpo** [comment]
> @andreicorpo Can you confirm that restarting the tmux server solves your problem?

Sorry, wasn't able to test it until now. Yes, it works now!
