### ISSUE TITLE
Use aliased tmux command?

### ISSUE THREAD

**Issue by jc00ke** [tmuxinator/tmuxinator#83]
Would it be possible to use the aliased version of the `tmux` command if one is present?

I have issues with 256 colors in `vim` inside `tmux` and the only way I've been able to solve it is by aliasing as follows:

```
alias tmux="TERM=screen-256color-bce tmux"
```

**Comment by tao12345666333** [comment]
You can use `tmux_command` option, setting  `tmux_command: tmux -2`
