### ISSUE TITLE
What variables are available to ERB?

### ISSUE THREAD

**Issue by wesbaker** [tmuxinator/tmuxinator#833]
In particular, when running the `start` command, are things like the name available?

```
tmuxinator start [project] -n [name] -p [project-config]
```

Beyond that, what else is available?

**Comment by ethagnawl** [comment]
You should be able to access anything in `env` and any optargs/kwargs passed to tmuxinator start. [See the ERB section of the README.](https://github.com/tmuxinator/tmuxinator#erb)
