### ISSUE TITLE
Is it possible to not show the session name in the bottom-left of the status bar?

### ISSUE THREAD

**Issue by ryanberckmans** [tmuxinator/tmuxinator#834]
Is it possible to not show the session name in the bottom-left of the status bar?

For example, the session name of `hello-tmuxinator` is highlighted in red below, is it possible to remove that?

![image](https://user-images.githubusercontent.com/299324/130329313-e002ace5-c34d-45d3-801d-44591a4f4181.png)

**Comment by ethagnawl** [comment]
This is really a tmux config concern (see `status-left` in `man tmux`) and there's currently no way to control this via tmuxinator config.

However, you could use tmuxinator hooks to manually change that value if you don't want to set it in your tmux.conf (i.e. you want it to only apply to your tmuxinator project and not all tmux sessions).

```
# foo.yml
...
on_project_start: tmux set -g status-left ""
...
```
