### ISSUE TITLE
docs(README.md):  the five standard layouts link is not working

### ISSUE THREAD

**Issue by halafi** [tmuxinator/tmuxinator#846]
**Describe the bug**
see title

**To Reproduce**
click *the five standard layouts*

**Comment by lyndsysimon** [comment]
This should be an easy fix. I'm looking for a good representation of the layouts now, and will submit a PR as soon as I find one that I like.

I'll update this comment as I find links that are "not quite right" for the docs but helpful if anyone else comes across this:

* https://dev.to/rajasegar/a-guide-to-create-tmux-like-custom-layouts-in-spacemacs-4j9p#layouts

**Comment by lyndsysimon** [comment]
I looked up [the original link in the Wayback Machine](http://web.archive.org/web/20211001000000*/http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html), and it didn't include any graphical of what the layouts look like.

I'll try to find something better, but for now I'll just submit a PR that updates the link to an online version of the manpage to replace the one that rotted.

**Comment by lyndsysimon** [comment]
PR submitted!

**Comment by ethagnawl** [comment]
Closed via #854.
