### ISSUE TITLE
tmuxinator autocomplete results in "Calling DidYouMean" deprecated error

### ISSUE THREAD

**Issue by Jeppelelle** [tmuxinator/tmuxinator#848]
> tmuxinator <tab> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

macOS 12.2
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
gem 3.0.3.1
tmuxinator 3.0.1

Installed & updated with Homebrew

Autocomplete worked fine up until yesterday, i think i ran 'brew upgrade' & ruby & ruby @3.0 got updated, the "DidYouMean" error seem to come from thor(?), i have never had that gem installed & "sudo gem install thor" did not fix the issue

Installing ruby with Homebrew & then running:
echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc:

ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]

Switching to latest ruby version still results in a "DidYouMean..." warning when trying to autocomplete with tmuxinator

Is the error message coming from thor? Do tmuxinator include it's own thor gem? Anyone else with the same issue? I can't seem to fix it

**Comment by mikeyp** [comment]
I think this is the upstream issue: https://github.com/rubygems/rubygems/issues/5234

**Comment by mikeyp** [comment]
I take that back, the issue seems to be in Thor: https://github.com/rails/thor/pull/761

Looks like version of Thor will need to be bumped.

**Comment by ethagnawl** [comment]
Thanks for digging into this, @mikeyp! I'll see about bumping the dependency and cutting a release.

**Comment by ethagnawl** [comment]
[tmuxinator 3.0.2 has been released](https://rubygems.org/gems/tmuxinator/versions/3.0.2) and contains the fix for this issue.
