### ISSUE TITLE
Update the links in the readme

### ISSUE THREAD

**Issue by laurinenas** [tmuxinator/tmuxinator#853]
The link to tmux man pages is broken:

`http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html#contenttoc6`

Removing named anchor would fix it too:

`http://manpages.ubuntu.com/manpages/jammy/en/man1/tmux.1.html`

**Comment by ethagnawl** [comment]
Thanks! However, this was just closed via #854.
