### ISSUE TITLE
Is startup_pane a string?

### ISSUE THREAD

**Issue by AlecRust** [tmuxinator/tmuxinator#871]
https://json.schemastore.org/tmuxinator.json specifies that `startup_pane` is a string.

Your documentation shows it as an integer:

```
# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1
```

**Comment by hyperupcall** [comment]
There is absolutely nothing that can be done about that here.

I opened an issue at https://github.com/SchemaStore/schemastore/issues/3308. If it doesn't get fixed by iteself in a few weeks, I might fix it myself.

**Comment by hyperupcall** [comment]
Fixed by https://github.com/SchemaStore/schemastore/pull/3311
