### ISSUE TITLE
Return of 'Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated'

### ISSUE THREAD

**Issue by mikeyjk** [tmuxinator/tmuxinator#875]
**Describe the bug**
A deprecation log warning when starting tmuxinator:

>Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

It looks like this is a return of an earlier issue, somehow: https://github.com/tmuxinator/tmuxinator/issues/848

**To Reproduce**
Start tmuxinator

**Expected behavior**
I don't see the log

**Environment**
- tmuxinator Version: tmuxinator 3.0.5
- tmux Version: tmux 3.0a
- Ruby Version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- OS: MacBook Pro, 16" 2019, intel i7

**Additional information**
I love this project! This is not a big deal, but I thought I'd raise it in case others get the same thing.

**Comment by akofink** [comment]
https://github.com/tmuxinator/tmuxinator/issues/848#issuecomment-1041972567
