### ISSUE TITLE
Enable use with wemux

### ISSUE THREAD

**Issue by athal7** [tmuxinator/tmuxinator#88]
I prefer to use wemux rather than tmux for remote pairing purposes, I was wondering if it would be possible to set an option in the config for a project to have it use wemux rather than tmux.

Thanks,
Andrew

**Comment by fsonntag** [comment]
When I try running 
tmuxinator start [project], I get the following error:                                                                                                                                                                                                        
undefined method `class_eval' for #<Tmuxinator::Project:0x00000002931528>
Same error also with debugging.
If I try my [project] with tmux it works completely fine. Anybody got some hints on that?

**Comment by athal7** [comment]
@fsonntag https://github.com/tmuxinator/tmuxinator/pull/453
