### ISSUE TITLE
Dependency ruby-thor is updated; this breaks tmuxinator on distros where ruby-thor has been updated

### ISSUE THREAD

**Issue by lervag** [tmuxinator/tmuxinator#883]
[ruby-thor](https://github.com/rails/thor/) has updated to version 1.3.0. This breaks the ~>1.2.1 dependency of tmuxinator:

    /usr/lib/ruby/3.0.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'thor' (~> 1.2.1) - did find: [thor-1.3.0] (Gem::MissingSpecVersionError)

The implication is that tmuxinator does not work properly when installed on e.g. Arch Linux through the [AUR](https://aur.archlinux.org/packages/tmuxinator) repos.

I updated the gemspec file and changed `~>1.2.1` to `~>1.3.0` for ruby-thor, which seems to fix this problem. I've not found any problems.

**Comment by lervag** [comment]
I believe the error is fixed by this PR: https://github.com/tmuxinator/tmuxinator/pull/882.

**Comment by Dstracke** [comment]
Yes, I did it with >=1.2.1, both ways should work.

**Comment by ethagnawl** [comment]
Fixed and available via [tmuxinator 3.1.0](https://rubygems.org/gems/tmuxinator/versions/3.1.0).

**Comment by lervag** [comment]
Thanks!
