### ISSUE TITLE
Support for TMUX 3.4

### ISSUE THREAD

**Issue by Drew-Daniels** [tmuxinator/tmuxinator#893]
**Is your feature request related to a problem? Please describe.**
I upgraded `tmux` this morning and when I launched `tmuxinator` saw this warning saying that this version of `tmux` is not supported.

![image](https://github.com/tmuxinator/tmuxinator/assets/62859552/07d7c128-83e3-446f-b12d-401f011f0faa)

**Describe the solution you'd like**
Update `lib/tmuxinator/tmux_version.rb` to include `3.4` in the list of supported versions of `tmux` (assuming there aren't breaking changes)

**Describe alternatives you've considered**

**Additional context**
I can still use `tmuxinator` without issues, so I'm guessing this is most likely a simple fix to whitelist this as a supported version, similar to [this issue](https://github.com/tmuxinator/tmuxinator/issues/861)

**Comment by Drew-Daniels** [comment]
Thanks for making the updates @akofink. 

Does the latest version of `tmuxinator` still need to be published? Looks like I'm not able to download the latest version of `tmuxinator`

```
❯ gem install tmuxinator
Fetching tmuxinator-3.1.0.gem

    __________________________________________________________
    ..........................................................

    Thank you for installing tmuxinator.

    Make sure that you've set these variables in your ENV:

      $EDITOR, $SHELL

    You can run `tmuxinator doctor` to make sure everything is set.
    Happy tmuxing with tmuxinator!

    ..........................................................
    __________________________________________________________

Successfully installed tmuxinator-3.1.0
Parsing documentation for tmuxinator-3.1.0
Installing ri documentation for tmuxinator-3.1.0
Done installing documentation for tmuxinator after 0 seconds
1 gem installed
```

**Comment by akofink** [comment]
Yes, I'm working on a release of tmuxinator 3.1.1 here: https://github.com/tmuxinator/tmuxinator/pull/897
