### ISSUE TITLE
Pane Titles Bugs (Parsing + Not Setting Multiple)

### ISSUE THREAD

**Issue by JaredStemper** [tmuxinator/tmuxinator#900]
**Parsing errors occur in providing special characters as well as setting multiple panes**
The recent feature to automatically set the pane title is extremely welcome, but currently has two notable bugs.

The first is when special characters, such as `(` or `)` are set in the pane title:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/36e286b9-0670-4cc8-8124-aaba8665d17a)

You will receive an error saying:
``` bash
sh: 37: Syntax error: "(" unexpected
```

The second notable error is that multiple pane titles are not parsed correctly.
Config:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/5b79893a-ab3e-4e4e-919b-9f10400354e5)
Session:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/07734288-c6e4-4f26-9840-6432b59c2eaf)
Error output:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/5c735568-3c1c-4112-ae30-d7e13cbd86c0)

It is somewhat interesting to note that the output is always less than the full list, suggesting that each pane title was attempted to be set but failed except the first.

`select-pane` to set the title manually still works (although the error output is still seen from the tmuxinator parsing).
Example config file:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/6b6d14a3-88f0-4c10-83f7-489a1620ec5b)
Example of created session using `select-pane`
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/bb60b5bc-78fd-4a93-9131-7ce1d1b6ce86)

**To Reproduce**
Create a config YAML file with a title using `(` or multiple panes.

**Environment**
 - tmuxinator Version: tmuxinator 3.1.1
- tmux Version: tmux 3.3a
 - Ruby Version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
 - OS: ![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/a990c642-91fe-4b5a-ab39-1a9230b236d9)

**Additional information**
Although primary testing was in Kali/Debian, it was noted that Ubuntu 20.04 had identical errors. 
OS details:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/68f58f6e-3bed-43f8-8abe-fc102ff0c72b)

**Fixes**
I have not delved very deep into the Tmuxinator codebase, but my best assumption for the multiple pane issue is that the target defined ![below](https://github.com/tmuxinator/tmuxinator/blob/3875617b1c6ec632ac6ac36d37b7d098aedbe738/lib/tmuxinator/pane.rb#L74) is not set correctly.
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/3c5990a3-d57d-4487-9caf-60e6edf05bc1)

For the parsing issue, I have a suspicion that simply wrapped the target in single quotes would work to solve this problem.

**Comment by akofink** [comment]
I notice this is also true of window names and could probably also be fixed in the same way, by wrapping with single quotes here: https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/window.rb#L111C18-L111C25
