### ISSUE TITLE
on_project_stop schema has type of string, when array or string can be parsed by tmuxinator

### ISSUE THREAD

**Issue by Drew-Daniels** [tmuxinator/tmuxinator#904]
**Describe the bug**
Apologies if this isn't the right place to create this, but I wasn't sure where to request this otherwise.

I am using `neovim` and the [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) to get code hints when editing my `yaml` files.

When editing one of my `tmuxinator` configuration files, the `yaml-language-server` is complaining that `on_project_stop` can only accept string values:

![image](https://github.com/tmuxinator/tmuxinator/assets/62859552/ac2a4ab9-7b7e-42a7-9faf-42918c1b5622)

If I set this value to a string, this warning goes away:

![image](https://github.com/tmuxinator/tmuxinator/assets/62859552/831a35a1-dedc-49ba-82e0-2773a7499e3a)

However, `tmuxinator` can parse `on_project_stop` settings with an array of values, making me think that our `tmuxinator` schema store file just needs to be updated to accurately reflect the possible value types we can use for this and other properties.

**To Reproduce**
- Install `neovim` with `brew`
- Install [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) with [mason](https://github.com/williamboman/mason.nvim)
- Install [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) and configure
```lua
lspconfig.yamlls.setup({})
```
- Open a `~/.config/tmuxinator/*.yaml` file
- Add an `on_project_stop` key with an array of commands
- See that you get a warning from the LSP saying that a string is expected for this property

**Expected behavior**
I would expect that the `tmuxinator` schema would match how we can configure our `tmuxinator` configuration files.

**Environment**
 - tmuxinator Version: tmuxinator 3.1.2
- tmux Version: tmux 3.4
 - Ruby Version: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
 - OS: 
 ```sh
                 ,xNMM.          -----------------------------------------
               .OMMMMo           OS: macOS 14.3 23D56 arm64
               OMMM0,            Host: Mac15,7
     .;loddo:' loolloddol;.      Kernel: 23.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 1 day, 1 hour, 25 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 69 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080, 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Rectangle
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: tmux
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Apple M3 Pro
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Apple M3 Pro
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 3360MiB / 18432MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

**Additional information**
I think that we might just need to update the [tmuxinator schemastore file](https://json.schemastore.org/tmuxinator.json) to be in sync with how we can actually configure `on_project_stop`
- At a glance, it looks like the `on_project_start`, `on_project_first_start`, `on_project_restart` and other properties also need to be updated similarly.

**Comment by augustelalande** [comment]
Thanks, I created a PR, https://github.com/SchemaStore/schemastore/pull/3672

**Comment by augustelalande** [comment]
@Drew-Daniels can you confirm whether your problem is fixed?
