### ISSUE TITLE
Unable to successfully run tmuxinator on macOS Sonoma 14.4.1

### ISSUE THREAD

**Issue by s5b** [tmuxinator/tmuxinator#909]
**Describe the bug**
A couple of weeks ago I was able to run a number of projects with `tmuxinator` on my Mac Book Pro without problem, as I have been doing for a number of years now. Today, however, running `tmuxinator` as I've always done simply opens any configured panes and runs the first command associated with each _pane_ and then stops.

**To Reproduce**
I appear to be unable run any of my existing projects, or any _new_ projects with `tmuxinator`. The problem is that all expected _panes_ open open start (good), but all commands are simply echoed at the top of each pane, and then only the first command appears to be executed. All subsequent commands are ignored.

**Expected behavior**
I expect each _pane_ to open, and for the commands _not_ to be echoed as a single block at the top of the _pane_, and for each command to be executed in sequence.

**Environment**
 - tmuxinator Version: `tmuxinator 3.1.2`
- tmux Version: `tmux 3.4`
 - Ruby Version: `ruby 2.5.5p157 (2019-03-15 revision 67260) [-darwin21]`
 - OS: `macOS Sonoma 14.4.1`

**Additional information**
Running this project will simply list the files in each `~/tmp/tmuxbuginator` directory, but will _not_ `cat` the contents of the two files:

```
name: tp-experiment
root: ~/tmp/tmuxbuginator

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# on_project_exit: tmux -CC attach
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf
# tmux_options: -f ~/.tmux.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false


windows:
  - main:
      layout: even-vertical
      panes:
        - core:
          - ls -al
          - cat core.txt
        - other:
          - ls -al
          - cat other.txt
```

**Comment by akofink** [comment]
This version of Ruby [went EOL on 2021-04-1](https://www.ruby-lang.org/en/downloads/branches/).

I tried to reproduce with the following environment without luck:

- tmuxinator Version: tmuxinator 3.1.2
- tmux Version: tmux 3.4
- Ruby Version: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
- OS: macOS Sonoma 14.4.1

I tried to install ruby 2.5.5 to test against that specific version but ran into an issue during build:

```
closure.c:264:14: error: call to undeclared function 'ffi_prep_closure'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    result = ffi_prep_closure(pcl, cif, callback, (void *)self);
```

Seems like my build tools can't build such an old ruby? 🤔 I will try again on another machine later.

**Comment by s5b** [comment]
@akofink Thank you so very much for your reply; very much appreciated.

Yes, that is a very old version of Ruby, and I wondered if that may be the cause. I'll aim to install a later version of Ruby and see if that makes a difference. 

Thanks again.

**Comment by s5b** [comment]
@augustelalande And thank you, too, for taking the time to look at my issue; also greatly appreciated.

The config that I posted is a simplified one that I created to demonstrate the problem. When I run it on my machine it appears to run the first command in each pane and then stops executing further commands. Also, all of the commands specific to a pane get echoed at the top of the pane prior to executing the first command. Could it be that the commands are not being separated into individual executions?

Thanks for your examination.

**Comment by augustelalande** [comment]
Could you provide a screen shot of what running your project looks like?

**Comment by s5b** [comment]
@augustelalande Here is a [link]([url](https://www.dropbox.com/scl/fi/8jir1gstmdp75j6fib8nd/2024-04-11-tmuxinator.mp4?rlkey=fy8vo77027107u6aopbynw3qp&dl=0)) to a video of me running the example that I posted above. I've simply removed the commented lines from the example to make it fit on the screen better.

You can see that it runs all of the commands in the top pane, but only runs the first command in the lower pane. This is what I experience when I have multiple panes: the top (first) pane appears to run all commands while the subsequent panes only run the first command.

Thanks.

**Comment by augustelalande** [comment]
Can you try this config
```
name: tp-experiment
root: ~/tmp/tmuxbuginator

windows:
  - main:
      layout: even-vertical
      panes:
        - ["ls -al", "cat core.txt"]
        - ["ls -al", "cat other.txt"]
```

**Comment by s5b** [comment]
@augustelalande 
That configuration works as I would expect. Thanks!

<img width="1702" alt="image" src="https://github.com/tmuxinator/tmuxinator/assets/380183/00c7c0f1-9223-478a-92c2-86503bc59760">

**Comment by augustelalande** [comment]
Nice. It's still a bug though, although I'm not really sure of the cause. Can you by chance test your original config with tmuxinator 3.1.0?

**Comment by s5b** [comment]
@augustelalande 

I've (`brew`) uninstalled `tmuxinator`, and installed `3.1.0` and I seem to have broken my installation … sigh.

I have a meeting to attend but will get back to it soon. Thanks for all your help.

**Comment by augustelalande** [comment]
Ouch, sorry about that. If it's too much trouble don't worry about it. Although I guess you are already in the weeds 😬.

**Comment by s5b** [comment]
Seriously in the weeds … I can't seem to get `tmuxinator` to install now - no matter which version I use. I'm using `rbenv`, so I updated the default version to already installed `ruby 3.0.4` by setting the `global` version (`~/.ruby-version`), and now I'm getting the following message:

```
/Users/sbegg/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem tmuxinator (>= 0.a) with executable tmuxinator (Gem::GemNotFoundException)
	from /Users/sbegg/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems.rb:282:in `activate_bin_path'
	from /Users/sbegg/.rbenv/versions/3.0.4/bin/tmuxinator:25:in `<main>'
```

¯\_(ツ)_/¯

**Comment by s5b** [comment]
Okay, I've managed to recover `tmuxinator` back to the latest version with the same _unusual_ behaviour. Phew, for that.

**Comment by s5b** [comment]
@augustelalande 

Finally, I got `tmuxinator` version `3.1.0` installed, and the _original_ configuration which was failing ran _without_ issue.

Version `3.1.0` did complain that I was running an _unsupported_ version of `tmux` (`3.4`), but when I told it to contue it worked correctly (for both versions of the config).

**Comment by augustelalande** [comment]
> Okay, I've managed to recover `tmuxinator` back to the latest version with the same _unusual_ behaviour. Phew, for that.

So even with the updated ruby the bug was still present?

**Comment by s5b** [comment]
@augustelalande Yes, the bug was still present. Just ran the original configuration with:

- tmuxinator 3.1.2
- tmux 3.4
- ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]

And got the same display of commands at the top of each pane, and only the first command being run in each pane.

<img width="1228" alt="image" src="https://github.com/tmuxinator/tmuxinator/assets/380183/8d7c5077-cf08-46f8-b5f3-7f40c574021a">

And running the _modified_ version of the configuration appears to run correctly. Albeit, with the commands still echoed at the top of each pane - I can't recall whether that's _normal_ or not. 

Also, curiously, I notice that the first pane of _echoed_ commands shows the change of directory, while the second pane does _not_ show the change of directory - even though the commands in the second pane are executed in the changed directory - which is correct execution behaviour. This is true for both examples.

<img width="1228" alt="image" src="https://github.com/tmuxinator/tmuxinator/assets/380183/42e0a444-dbf6-421f-b8e1-b123df242747">


Thanks.

**Comment by augustelalande** [comment]
@akofink could you make a new release so we can see if the problem still exists with the few changes that were made?

**Comment by akofink** [comment]
I will create a new release. There are quite a few changes, so I'm bumping the minor / y version to 3.2.0.

I still haven't been able to reproduce this, but if you can reproduce reliably, it would be best to check out the repo and run against `master` so we can leverage `git bisect` to find the commit that introduced the issue. Based on the info in this issue, it seems like it's somewhere between tmuxinator 3.1.0 and 3.1.2. I am suspicious of [this change](https://github.com/tmuxinator/tmuxinator/pull/891), simply because it changes the pane code.

[This line in particular seems fishy](https://github.com/tmuxinator/tmuxinator/pull/891/files#diff-ca83b46c481c5d0317d4a17511b14adc1adf5c6631ec740db76a1b47254be058R55) because it calls `.first`. So, the way I'm reading that, if you supply a `Hash` as a pane config, it will only see the first key/value pair. 🤔

I can try and debug this more and try to see why/if I can reproduce with the debugger.

**Comment by akofink** [comment]
tmuxinator 3.2.0 is now available

https://rubygems.org/gems/tmuxinator/versions/3.2.0
https://github.com/tmuxinator/tmuxinator/releases/tag/v3.2.0

**Comment by augustelalande** [comment]
> I am suspicious of [this change](https://github.com/tmuxinator/tmuxinator/pull/891)

me too

> [This line in particular seems fishy](https://github.com/tmuxinator/tmuxinator/pull/891/files#diff-ca83b46c481c5d0317d4a17511b14adc1adf5c6631ec740db76a1b47254be058R55) because it calls .first. So, the way I'm reading that, if you supply a Hash as a pane config, it will only see the first key/value pair.

With a config a follows
```yaml
windows:
  - window1:
      layout: main-vertical
      panes:
        - pane1:
          - command1
          - command2
```
`pane_yml` corresponds to any item in the `panes` list. In this case:
```yaml
pane1:
      - command1
      - command2
```
which is a Hash with a single key. `pane_yml.values.first` is then the value associated with the first key. In this case a list
```yaml
- command1
- command2
```

regardless, since the issue only appears on some systems (could be a macOS issue) it would imply some system dependent difference between ruby (unlikely), or one of our dependencies.

**Comment by s5b** [comment]
@akofink : Thanks for the new release `3.2.0`.
@augustelalande : Thanks for your continued assistance.

I've installed the new release via `brew` and rerun the same _example_ configurations against the new version.

* macOS: Sonoma 14.4.1
* ruby: 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]
* tmux: 3.4
* tmuxinator: 3.2.0

The original _list_ version still exhibits the _bug_, whereby it only executes the first command of the command **list**.

The modified _array_ version (shown below) runs all of the commands, as expected.

![2024-04-19-tmuxinator-bug](https://github.com/tmuxinator/tmuxinator/assets/380183/c86379e8-a7e3-4bfe-ac5f-7593aafe8521)

I've been suspicious of the `yaml` processing throughout this investigation. I will attempt the _bisect_ over the weekend and see if I can narrow down the _commit_ that introduced the change.

As a complete aside: I don't recall the commands being echoed at the top of each _pane_ in the past, but maybe I just wasn't paying attention - and also that's prolly related to tmux, and not to tmuxinator.

**Comment by augustelalande** [comment]
Ok I think I know what the issue is, although I'm not sure how to fix it yet.

What's happening (I think) is a race condition between these lines which send the pane commands
https://github.com/tmuxinator/tmuxinator/blob/52204947a0edbed4b633f8f1eee119002c8e2086/lib/tmuxinator/assets/template.erb#L71-L79
and the shell initialization which must take place for each pane before the commands can be executed.

This is also why the commands appear at the top of the pane. If you've ever tried to type into a console when it wasn't ready to accept input, this is the same behavior.

Typically, if you type `command1<enter>command2<enter>` before the shell is ready, it will execute command1 and then command2 once ready. I'm hypothesizing in your (@s5b) setup it will only execute command1.

This race condition probably existed in tmuxinator for a while, but it seems to have been made worse by
https://github.com/tmuxinator/tmuxinator/blob/52204947a0edbed4b633f8f1eee119002c8e2086/lib/tmuxinator/assets/template.erb#L68-L70
which seems to lengthen the pane initialization.

**Comment by s5b** [comment]
@augustelalande - My `zsh` startup is quite slow; I expect this is caused by a number of _helper_ extensions that require time to get going on initialisation. I can see why, as you write, that a slow starting shell may contribute to why I see the problem when others don't experience the same results. Thanks for your ongoing support.

PS: I ran out of time over the weekend to try the _bisect_, but will try to get to it over the next day or so.

**Comment by s5b** [comment]
@augustelalande  @akofink  I've finally been able to run the `tmuxinator 3.1.2` release, installed via `brew`. And this version runs as I would expect - meaning that it does not exhibit the erroneous behaviour I've reported for the later releases.

The working configuration is:
* **macOS**: `14.14.1`
* **ruby**: `3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]`
* **tmux**: `3.4`
* **tmuxinator**: `3.1.2`

Again, thanks for your help with this issue.

**Comment by s5b** [comment]
Just tried the recent version of `tmuxinator`, via `brew`: it's still _broken_ for me in the same way; unfortunately unusable. 😞

The configuration is:

* macOS: `Sonoma 14.5`
* ruby: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]`
* tmux: `3.4`
* tmuxinator: `3.2.1`

**Comment by augustelalande** [comment]
> @augustelalande @akofink I've finally been able to run the `tmuxinator 3.1.2` release, installed via `brew`. And this version runs as I would expect - meaning that it does not exhibit the erroneous behaviour I've reported for the later releases.
> 
> The working configuration is:
> 
> * **macOS**: `14.14.1`
> * **ruby**: `3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]`
> * **tmux**: `3.4`
> * **tmuxinator**: `3.1.2`
> 
> Again, thanks for your help with this issue.

I didn't notice, but your saying 3.2.1 is working? So then it woudn't be a problem with #891.

@akofink could it be a problem with `erubi`?

**Comment by akofink** [comment]
> could it be a problem with erubi?

It certainly could be! If I could reproduce this myself, I would run `git bisect` to confirm the change that introduced the regression. It would be really helpful to get a reliable reproducer, like in a container image, but this may be OS X specific.

**Comment by akofink** [comment]
I just realized there is a `debug` command as I was attempting to add one! 🤦

This outputs the project config right before it would be evaluated by ruby, e.g.

```
$ tmuxinator debug tpexperiment
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /tmp

# Run on_project_start command.



  # Run pre command.


  # Run on_project_first_start command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s tpexperiment -n main -c /tmp



  # Create other windows.


  # Window "main"


  tmux select-pane -t tpexperiment:1.1 -T core
  tmux send-keys -t tpexperiment:1.1 ls\ -al C-m
  tmux send-keys -t tpexperiment:1.1 cat\ core.txt C-m

  tmux splitw -c /tmp -t tpexperiment:1
  tmux select-layout -t tpexperiment:1 tiled
  tmux select-pane -t tpexperiment:1.2 -T other
  tmux send-keys -t tpexperiment:1.2 ls\ -al C-m
  tmux send-keys -t tpexperiment:1.2 cat\ other.txt C-m

  tmux select-layout -t tpexperiment:1 tiled

  tmux select-layout -t tpexperiment:1 even-vertical
  tmux select-pane -t tpexperiment:1.1


  tmux select-window -t tpexperiment:1
  tmux select-pane -t tpexperiment:1.1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t tpexperiment
  else
    tmux -u switch-client -t tpexperiment
  fi



# Run on_project_exit command.
```

You can see the relevant two commands, as expected in my output:

```
  tmux send-keys -t tpexperiment:1.2 ls\ -al C-m
  tmux send-keys -t tpexperiment:1.2 cat\ other.txt C-m
```

Curious what you see!

**Comment by s5b** [comment]
@akofink Thanks for your reply. To be clear, the current version of `trmuxinator` , version `3.2.1` via `brew`, is exhibiting the same _erroneous_ behaviour as I first reported. That is, it doesn't appear to run all of the specified commands from the configuration in all of the configured _panes_.

As requested above, here is the _debug_ output.

I used the following configuration:  `experiment.yml`

```yaml
name: tp-experiment
root: ~/tmp/tmuxbuginator

windows:
  - main:
      layout: even-vertical
      panes:
        - core:
          - ls -al
          - cat core.txt
        - other:
          - ls -al
          - cat other.txt
```

And then ran this command: `tmuxinator debug experiment`

To get this output:

```zsh
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /Users/sbegg/tmp/tmuxbuginator

# Run on_project_start command.



  # Run pre command.


  # Run on_project_first_start command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s tp-experiment -n main -c /Users/sbegg/tmp/tmuxbuginator



  # Create other windows.


  # Window "main"


  tmux select-pane -t tp-experiment:1.1 -T core
  tmux send-keys -t tp-experiment:1.1 ls\ -al C-m
  tmux send-keys -t tp-experiment:1.1 cat\ core.txt C-m

  tmux splitw -c /Users/sbegg/tmp/tmuxbuginator -t tp-experiment:1
  tmux select-layout -t tp-experiment:1 tiled
  tmux select-pane -t tp-experiment:1.2 -T other
  tmux send-keys -t tp-experiment:1.2 ls\ -al C-m
  tmux send-keys -t tp-experiment:1.2 cat\ other.txt C-m

  tmux select-layout -t tp-experiment:1 tiled

  tmux select-layout -t tp-experiment:1 even-vertical
  tmux select-pane -t tp-experiment:1.1


  tmux select-window -t tp-experiment:1
  tmux select-pane -t tp-experiment:1.1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t tp-experiment
  else
    tmux -u switch-client -t tp-experiment
  fi



# Run on_project_exit command.
```

Running without `debug` gives this output: which lists the commands at the top of each pane, but _**does not**_ run the `cat` command in the bottom pane.

<img width="897" alt="image" src="https://github.com/tmuxinator/tmuxinator/assets/380183/11fe3dcb-4c0e-4656-a953-5d95bc46a28a">


All run in this environment:

* macOS: `Sonoma 14.5 (23F79)`
* hardare: MacBook Pro M1
* ruby: `3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]`
* tmux:  `3.4`
* tmuxinator: `3.2.1`

**Comment by akofink** [comment]
The debug output looks fine to me. I even ran it myself after tweaking the file paths to work on my machine. I ran it like this:

```
bash s5b.sh
```

And it looks like this, which looks correct to me:

<img width="1470" alt="Screenshot 2024-06-01 at 09 31 44" src="https://github.com/tmuxinator/tmuxinator/assets/761923/25997fad-0f35-490f-8d12-a3e90a1631e7">


My environment:
- macOs 14.5
- MacBook Air M2
- ruby `ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin23]` (I have tried several other ruby versions)
- tmux `3.4`
- tmuxinator on `master` / `0f7e9ff` / `v3.2.1`

It looks like you're using zsh, as am I. Maybe you could try running your debug output via `bash` or `zsh` directly instead, like I did above. You might try it with an empty `.zshrc` just to be sure it's not something related to your shell config.

**Comment by s5b** [comment]
@akofink Interesting reply, thanks.

I tried a bunch of things related to your comments above, and found the following:

## Running the debug output with `bash`, from `zsh`

Without changing anything else, I tried running the _debug_ output with `bash`. That is, starting `bash` (version `5.2`, from `brew`) from a `zsh` shell, with my `~/.zshrc` file in play.

Ran: `bash s5b.sh`. 

Result: Opened two panes, printed all of the command in the respective panes. Ran all of the commands in the first pane. Only ran the first command in the second pane. (fail)

## Running the debug output with `bash`, from `zsh` (without `~/.zshrc`)

I tried running the _debug_ output with `bash`. That is, starting `bash` (version `5.2`, from `brew`) from a `zsh` shell, started **without** my `~/.zshrc` file in play: `exec zsh -i -f -d`

Ran: `bash s5b.sh`. 

Result: Opened two panes, printed all of the command in the respective panes. Ran all of the commands in the first pane. Only ran the first command in the second pane. (fail - same as above)

## Running with `bash` set as the default shell in `tmux`, from `zsh`

Set the following _configuration_ in `~/.tmux.conf`:

```
set-option -g default-shell /opt/homebrew/bin/bash
```

Ran the following command from `zsh`, without `~/.zshrc` in play.

Ran: `tmuxinator experiment`

Result: Displays two panels. Prints out the commands to be run at the top of each respective panel. Displays the command prompt (in the correct directory) in each panel. Does NOT run any of the commands.

However, activating each panel in turn, and typing the `ENTER` key in each panel causes all of the respective commands for that panel to run in that panel. ¯\_(ツ)_/¯

# Closing this issue

It appears that I'm the only person experiencing this issue. I _have_ seen the commands run as they should once during all of these changes, giving me a kind of _false_ hope, but it is non-deterministic - for me. I'm going to stop consuming everybody's time on this issue (my issue) now, including my own, and close this issue now.

**Thank you to all who responded. I _really_, _really_ appreciate the extended effort that was made in looking for a solution.**

**Comment by akofink** [comment]
The behavior you were seeing seems fairly similar to https://github.com/tmuxinator/tmuxinator/issues/856

**Comment by s5b** [comment]
@akofink Thank you for the reference; _very_ much appreciated.
