### ISSUE TITLE
`project.root` property is "overridden" by `windows.first.root`

### ISSUE THREAD

**Issue by Krismix1** [tmuxinator/tmuxinator#916]
**Describe the bug**
When using version 3.2.1, if `windows.first.root` is defined, it overrides the `project.root` configuration - starting new windows with `tmux` will start the shell at `windows.first.root` instead of `project.root`.

I believe this is caused by the recently added `-c` in `tmux new-session` (see the output of `tmuxinator debug` below) in version 3.2.1.
I have compared the behaviour to 3.2.0, and in 3.2.0 it works as I expect (the culprit is possibly #914).
In 3.2.0 the `windows.first.root` used `cd`, which only affected the shell itself. Whereas `-c` changes the tmux session.

I have found a workaround for myself: detach the tmux session and reattach to it using `-c <project.root>` arg.
Integrated this with an `on_project_exit` hook, e.g. `on_project_exit: tmux attach-session -t bug -c ~/parent`

**To Reproduce**
On version 3.2.1, use the following config:
```yaml
name: bug
root: ~/parent

windows:
  - dir2:
      root: ~/parent/dir2
  - dir1:
      root: ~/parent/dir1
```

Start the session:
```bash
mkdir -p ~/parent/dir{1,2}
tmuxinator start sample
```
Create a new window in tmux. The current working directory is set to `~/parent/dir2` instead of `~/parent`.

**Expected behavior**
When creating new windows in the given session, I expect the new window to be created at the path `~/parent`.
This however does not happen; the new window is created at `~/parent/dir2`.

**Environment**
 - tmuxinator Version: tmuxinator 3.2.1
- tmux Version: tmux 3.4
 - Ruby Version: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
 - OS: Arch Linux

**Additional information**
Output of `tmuxinator debug bug` using 3.2.1:
```sh
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /home/user/parent

# Run on_project_start command.



  # Run pre command.


  # Run on_project_first_start command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s bug -n dir2 -c /home/user/parent/dir2



  # Create other windows.
  tmux new-window -c /home/user/parent/dir1 -t bug:2 -n dir1


  # Window "dir2"




  # Window "dir1"




  tmux select-window -t bug:1
  tmux select-pane -t bug:1.1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t bug
  else
    tmux -u switch-client -t bug
  fi



# Run on_project_exit command.
```

Output of `tmuxinator debug sample` using 3.2.0:
```sh
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /home/user/parent

# Run on_project_start command.



  # Run pre command.


  # Run on_project_first_start command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s bug -n dir2
  tmux send-keys -t bug:1 cd\ /home/user/parent/dir2 C-m



  # Create other windows.
  tmux new-window -c /home/user/parent/dir1 -t bug:2 -n dir1


  # Window "dir2"


  # Window "dir1"


  tmux select-window -t bug:1
  tmux select-pane -t bug:1.1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t bug
  else
    tmux -u switch-client -t bug
  fi



# Run on_project_exit command.
```

**Comment by akofink** [comment]
Thank you for reporting this and for the detailed report!

I reverted #914 locally, and it seems to fix the issue.

Instead of just reverting that change, [I've attempted to cut down on the `cd` commands leveraging `-c` while also fixing the session path](https://github.com/tmuxinator/tmuxinator/pull/917).

**Comment by akofink** [comment]
The fix for this will be in the next release - thank you again for reporting it! 🎉

**Comment by Krismix1** [comment]
Thank you @akofink for taking care of it!
