### ISSUE TITLE
Exit tmuxinator project session

### ISSUE THREAD

**Issue by vighnesh1987** [tmuxinator/tmuxinator#92]
It'd be neat to have a feature which allows you to exit a tmuxinator project session safely i.e.
for a pane running vim, it first does a :qa, followed by a <C-D> to close the pane,
for a pane running a server, it does a <C-C> followed by <C-D>

The exact commands could be specified in the project yaml file.

Comments?

**Comment by Soliah** [comment]
Closing in favour of jlipps/tmux-safekill.

**Comment by ccmcbeck** [comment]
If you get here because `tmux` is not reliably killing `rails server`, you should know that it does reliably kill `heroku local`.  Sometimes, I use `rails server` to run `byebug`, but now I always try to use `heroku local` in a tmux YML file.

**Comment by unlessbamboo** [comment]
+1， tmux-safekill
