### ISSUE TITLE
Unable to start sessions due to "TMUX= tmux new-session ..."

### ISSUE THREAD

**Issue by edman** [tmuxinator/tmuxinator#924]
**Describe the bug**
Given a config such as

```
name: sample
root: ~/
windows:
  - editor:
      layout: main-horizontal
      panes:
        - nvim
```

Trying to start it produces the error

```
$  tmuxinator start sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
can't find session: sample
```

After this `tmux ls` shows no new sessions.

Running `tmuxinator start sample` a second time prints the message `duplicate session: sample` before printing the same `can't find session: sample` as above. I still don't see the `sample` session in `tmux ls`.

In `tmuxinator debug sample` I see the following command to start the session (note the `TMUX=<space>` prefix):

```
TMUX= tmux new-session -d -s sample -n editor
```

It seems this causes `tmux new-session` to run in a new tmux server, not the one I'm currently in. The following calls to `tmux` in the script don't have the `TMUX=<space>`, so they run on the current server, which doesn't have the newly created `sample` session. Hence all the error messages.

**To Reproduce**
1. `tmuxinator create sample`
2. `tmuxinator start sample`

**Expected behavior**
The new `sample` session starts.

**Environment**
 - tmuxinator Version: 3.0.5
- tmux Version: tmux 3.3a
 - Ruby Version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
 - OS: Debian 6.6.15-2rodete2 (2024-03-19) x86_64 GNU/Linux (from `uname -a`)

**Additional information**
This seems similar to https://github.com/tmuxinator/tmuxinator/issues/829, but I don't think it's the same. A `tmux kill-server` didn't help.

As a workaround I use the following function in my zshrc to remove the `TMUX=<space>` from `tmuxinator debug` before running it.

```
function tmuxinator_start() {
  # run it like:
  #   tmuxinator_start <project>
  tmuxinator debug "$1" | sed 's/TMUX= //' | sh
}
```

**Comment by akofink** [comment]
Are you trying to start this sample project from within an existing tmux session? The TMUX variable should be unset outside of tmux sessions. If you run `tmux start-session` from within an existing session without unsetting TMUX, you get this error:

```
# From within a tmux session
$ tmux
sessions should be nested with care, unset $TMUX to force
```

**Comment by edman** [comment]
I did run it from within a tmux session, but I don't mind that it creates a new session within the same server (that's what my `tmuxinator_start` workaround does).

The script created by tmuxinator calls `tmux new-session -d`, which shouldn't create a nested session.
