### ISSUE TITLE
Support for Tmux 3.5

### ISSUE THREAD

**Issue by Drew-Daniels** [tmuxinator/tmuxinator#928]
**Is your feature request related to a problem? Please describe.**
`tmux` just released `v3.5` a few hours ago, and when I ran `brew update` this morning, I got the latest version of `tmux` installed.

**Describe the solution you'd like**
Similar request to [893](https://github.com/tmuxinator/tmuxinator/issues/893), but just requesting that `tmux 3.5` be added to the list of supported `tmux` versions for `tmuxinator`.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/dc7e61fd-3b8f-4d9c-b221-06ea932c4e36)

Thanks for all the work you do maintaining this package! It's massively useful for my development workflow.

**Comment by augustelalande** [comment]
FYI a PR was already opened #927

**Comment by akofink** [comment]
Fixed with https://github.com/tmuxinator/tmuxinator/pull/927
