### ISSUE TITLE
Tmuxinator doesn't work when the project name contains a dot

### ISSUE THREAD

**Issue by florian** [tmuxinator/tmuxinator#93]
If the `project_name` contains a dot  like `project.js` and I start the project with `$ mux project.js` then Tmuxinator will start a plain tmux session, ignoring all the Tmuxinator settings.

I guess this isn't maintained anymore, but I'll just report this, in case anybody is wondering why Tmuxinator silently fails.

**Comment by gvlasov** [comment]
@Soliah Why not have a translation layer between the filename and session name? E.g. replacing `.`s from the filename with `_`s or maybe with a longer string like `_$_` to lower the chances of a collision with another session whose filename actually uses `_` in place of `.`?
