### ISSUE TITLE
Ability to list all active `tmuxinator` projects

### ISSUE THREAD

**Issue by Drew-Daniels** [tmuxinator/tmuxinator#933]
**Is your feature request related to a problem? Please describe.**
This is somewhat related to https://github.com/tmuxinator/tmuxinator/issues/932, but sometimes I want to see what `tmuxinator` projects I have running, as opposed to all `tmux` sessions (that may not have been created using a `tmuxinator` project config)

Ex.)
```sh
# start up a couple tmuxinator projects
$ tmuxinator start dotfiles
$ tmuxinator start work

# start up a random tmux session
$ tmux new-session -s test

# I want to see active tmuxinator projects
# but "tmux ls" shows all tmux sessions, not just running tmuxinator projects
$ tmux ls

dotfiles: 1 windows (created Tue Oct 15 14:21:01 2024)
work: 1 windows (created Tue Oct 15 14:24:31 2024)
test: 1 windows (created Tue Oct 15 14:39:18 2024)
```

**Describe the solution you'd like**
There is a `tmuxinator ls` command already but I think it would be nice if there were a way to run `tmuxinator ls --running` or `tmuxinator ls-active`, or something along those lines to see what `tmuxinator` projects I have running.

**Describe alternatives you've considered**

**Additional context**

**Comment by Drew-Daniels** [comment]
@akofink thanks for adding this!

Just wondering, do you have an idea of when the next release for `tmuxinator` will be? Looking forward to using this feature.

**Comment by akofink** [comment]
Hey @Drew-Daniels, I will make a release this week.
