### ISSUE TITLE
auto setting RBENV_VERSION

### ISSUE THREAD

**Issue by take** [tmuxinator/tmuxinator#99]
Seems like tmuxinator is auto setting RBENV_VERSION.

Which leads to a problem that .ruby-version doesn't affect the ruby version since RBENV_VERSION is favored over .ruby-version :(

Of course when I use normal tmux, this doesn't happen.

I'm using tmux 1.7 and tmuxinator 0.5.0

**Comment by fffx** [comment]
I use this

    pre_window: if [[ -f ".ruby-version" ]] &&  [[ -f ".ruby-gemset" ]]; then rvm use $(cat .ruby-version)@$(cat .ruby-gemset); fi
